### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by wke102** [OneWayTech/vue2-datatable#1]
How can i require them in my app.js file?

Can't seem to require this component, doesn't seem to have Datatable.vue main file component?

**Comment by kenberkeley** [comment]
see https://github.com/OneWayTech/vue2-datatable/blob/master/package.json#L6

**Comment by kenberkeley** [comment]
```js
import Datatable from 'vue2-datatable-component'
// as same as
import Datatable from 'vue2-datatable-component/lib/index.vue'
```

**Comment by wke102** [comment]
Am still having problems here tried import and require but still getting errors...

Any idea how to fix this?

[23:50:50] Using gulpfile /Applications/MAMP/htdocs/laravel5/gulpfile.js
[23:50:50] Starting 'all'...
[23:50:50] Starting 'sass'...
[23:50:51] Finished 'sass' after 390 ms
[23:50:51] Starting 'webpack'...
{ [Error: ./~/buble-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vue2-datatable-component/lib/index.vue
Module not found: Error: Can't resolve './HeadSort' in '/Applications/MAMP/htdocs/laravel5/node_modules/vue2-datatable-component/lib'
resolve './HeadSort' in '/Applications/MAMP/htdocs/laravel5/node_modules/vue2-datatable-component/lib'
  using description file: /Applications/MAMP/htdocs/laravel5/node_modules/vue2-datatable-component/package.json (relative path: ./lib)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Applications/MAMP/htdocs/laravel5/node_modules/vue2-datatable-component/package.json (relative path: ./lib)
    using description file: /Applications/MAMP/htdocs/laravel5/node_modules/vue2-datatable-component/package.json (relative path: ./lib/HeadSort)
      as directory
        /Applications/MAMP/htdocs/laravel5/node_modules/vue2-datatable-component/lib/HeadSort doesn't exist
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /Applications/MAMP/htdocs/laravel5/node_modules/vue2-datatable-component/lib/HeadSort doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /Applications/MAMP/htdocs/laravel5/node_modules/vue2-datatable-component/lib/HeadSort.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        /Applications/MAMP/htdocs/laravel5/node_modules/vue2-datatable-component/lib/HeadSort.json doesn't exist
[/Applications/MAMP/htdocs/laravel5/node_modules/vue2-datatable-component/lib/HeadSort]
[/Applications/MAMP/htdocs/laravel5/node_modules/vue2-datatable-component/lib/HeadSort]
[/Applications/MAMP/htdocs/laravel5/node_modules/vue2-datatable-component/lib/HeadSort.js]
[/Applications/MAMP/htdocs/laravel5/node_modules/vue2-datatable-component/lib/HeadSort.json]
 @ ./~/buble-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vue2-datatable-component/lib/index.vue 101:0-33
 @ ./~/vue2-datatable-component/lib/index.vue
 @ ./resources/assets/js/app.js./~/buble-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vue2-datatable-component/lib/index.vue
Module not found: Error: Can't resolve './LimitSelect' in '/Applications/MAMP/htdocs/laravel5/node_modules/vue2-datatable-component/lib'
resolve './LimitSelect' in '/Applications/MAMP/htdocs/laravel5/node_modules/vue2-datatable-component/lib'
  using description file: /Applications/MAMP/htdocs/laravel5/node_modules/vue2-datatable-component/package.json (relative path: ./lib)
    Field 'browser' doesn't contain a valid alias configuration
