### ISSUE TITLE
Component Render Issue

### ISSUE THREAD

**Issue by CONDEV9** [OneWayTech/vue2-datatable#10]
Wanted to add this component to a existing project, followed the instructions and nothing is showing as well as no errors in the console.

`<datatable />` is replaced with `<!--function (e,n,r,o){return re(t,e,n,r,o,!0)}-->`

If i add `import Datatable from '../../../node_modules/vue2-datatable-component/lib/index.vue'` where i want to use this component it start to work. In an other test project i can use `<datatable />` globally without to import it.

**Comment by kenberkeley** [comment]
What's the meaning of `<datatable /> is replaced with <!--function (e,n,r,o){return re(t,e,n,r,o,!0)}-->`

**Comment by CONDEV9** [comment]
Here is a illustration, the block with `<datatable> `
![screenshot_1](https://user-images.githubusercontent.com/19559651/29772210-5bc46a1e-8c00-11e7-99dc-6d9bd52d2653.png)

is rendered in the bowser like this

![screenshot_2](https://user-images.githubusercontent.com/19559651/29772208-5ba2f596-8c00-11e7-9ca9-0f6e44e4c9b0.png)

**Comment by kenberkeley** [comment]
no idea...

**Comment by CONDEV9** [comment]
If i import it like this, it is shown but that not how it should work, right?

```
<script>
  import Datatable from '../../../node_modules/vue2-datatable-component/lib/index.vue'

  export default {
    components: {
      Datatable
    },
    data: () => ({
      supportBackup: true,
      supportNested: true,
      tblClass: 'table-bordered',
      columns: [
        {title: 'ID', field: '_id', visible: false},
        {title: 'Name', field: 'name'},
        {title: 'Reference', field: 'reference'}
      ],
      data: [],
      total: 0,
      selection: [],
      query: {}
    })
  }
</script>
```

main.js
```
import Vue from 'vue'
import App from './App'
import router from './router'

import VueResource from 'vue-resource'
import VueI18n from 'vue-i18n'
import VueNoty from 'vuejs-noty'
import Datatable from 'vue2-datatable-component'

import messages from './locales'
import { store } from './store'

Vue.use(VueResource)
Vue.use(VueI18n)
Vue.use(VueNoty)
Vue.use(Datatable)
Vue.config.productionTip = false

const i18n = new VueI18n({
  locale: localStorage.getItem('language'),
  fallbackLocale: 'en',
  messages
})

/* eslint-disable no-new */
new Vue({
  el: '#app',
  router,
  i18n,
  store,
  render: h => h(App)
})
```

**Comment by kenberkeley** [comment]
The previous version may conflict with vue-i18n. Try update to the latest.

**Comment by kenberkeley** [comment]
you have already registered it globally, so I have no idea why only local registration worked

**Comment by CONDEV9** [comment]
Already on 1.1.10 and tried vue-i18n version 5.0.3 and the latest 7.2.0, unfortunately same issue.

**Comment by kenberkeley** [comment]
sorry for not helping you

**Comment by stevefermi** [comment]
same problem

**Comment by kenberkeley** [comment]
I need a demo to reproduce, please?

**Comment by stevefermi** [comment]
I've created a repo [here](https://github.com/stevefermi/vue2data-test)

I cannot run it since it told me that **template or render function is not defined as below**

![image](https://user-images.githubusercontent.com/10499297/30522054-7f735972-9b8f-11e7-9f63-b62b42fcdb14.png)

I followed the instruction except the mock data and I am not sure if it is related to that.

**Comment by kenberkeley** [comment]
Temporary solution: 

```js
import Vue from 'vue'
import Datatable from 'vue2-datatable-component/dist/min.js'
import 'vue2-datatable-component/dist/min.css'

Vue.use(Datatable)
```

**Comment by kenberkeley** [comment]
fixed in https://github.com/OneWayTech/vue2-datatable/commit/0af2add593e464825736a2a6d843753150b52508
