### ISSUE TITLE
Is it possible to change pagination length?

### ISSUE THREAD

**Issue by Dameon87** [OneWayTech/vue2-datatable#100]
Hey there, I was wondering if it's possible to change the length of the pagination. For example, It currently shows entries for Pages 1,2,3,4,5,6,7,..., and the last page. Is it possible to trim these down a bit, as I'm having trouble on mobile devices with the pagination length exceeding the page width.

**Comment by kenberkeley** [comment]
[DIY](https://onewaytech.github.io/vue2-datatable/doc/#/en/DIY)
