### ISSUE TITLE
Allow removing default classes from table element

### ISSUE THREAD

**Issue by flyingL123** [OneWayTech/vue2-datatable#105]
Is there any way to remove classes from the table element? I would like to remove the `table-striped` class, but I don't see how.

The `tblClass` prop let's me add classes, but how I can remove some of the ones that are being added automatically?

**Comment by kenberkeley** [comment]
According to https://github.com/OneWayTech/vue2-datatable/blob/master/src/Table/TableFrame.vue#L2

`table-striped` is hard coded...

so... well... how about:

```js
$('.table-striped').removeClass('table-striped')
```
