### ISSUE TITLE
Sorting arrow icon classes are incorrect

### ISSUE THREAD

**Issue by flyingL123** [OneWayTech/vue2-datatable#109]
I think the class on the icons for descending and ascending sorting is incorrect. The library applies the classes `fa-sort-desc` and `fa-sort-asc`, but the actual classes from fontawesome are `fa-sort-up` and `fa-sort-down`:

https://fontawesome.com/icons?d=gallery&q=sort

**Comment by flyingL123** [comment]
Here's a PR https://github.com/OneWayTech/vue2-datatable/pull/110

**Comment by kenberkeley** [comment]
![image](https://user-images.githubusercontent.com/13287948/39610911-20ef4da6-4f86-11e8-8370-cac42c2f8259.png)

**Comment by kenberkeley** [comment]
FontAwesome V4

**Comment by kenberkeley** [comment]
https://github.com/OneWayTech/vue2-datatable/commit/9b99e43c1ddd68914a3b7ce12d2a29893677ef0b
