### ISSUE TITLE
string columns not sortable

### ISSUE THREAD

**Issue by Masber** [OneWayTech/vue2-datatable#111]
as the title says, columns with string values are not sortable.

example:

```
        columns: [
        	{ title: 'Name', field: 'firstName', sortable: true },
        	{ title: 'Contact Number', field: 'contactNumber' },
        	{ title: 'Email', field: 'email', sortable: true },
          	{ title: 'Address', field: 'address' },
          	{ title: 'Suburb', field: 'suburb', sortable: true },
          	{ title: 'State', field: 'state', sortable: true },
   		{ title: 'Country', field: 'country', sortable: true }
        ],
```
None of the data of any of the columns above gets sorted...

Any reason for that?

**Comment by kenberkeley** [comment]
It's done by backend

https://github.com/OneWayTech/vue2-datatable/blob/master/examples/src/_mockData/index.js#L35

**Comment by archimedix** [comment]
Is not possible to do it by client, as number columns?

**Comment by kenberkeley** [comment]
@archimedix https://github.com/OneWayTech/vue2-datatable/blob/master/examples/src/_mockData/index.js#L34-L36

**Comment by IceOnFire** [comment]
Hi @kenberkeley,

I'll try to rephrase it: even when you put `sortable: true` on a string column, the little arrows that allow sorting do not even show up on the table header, thus preventing any possibility to sort on the server.

There is no example on the website that shows sorting of string columns, just numbers. Maybe this feature was never thought of?

**Comment by kenberkeley** [comment]
i said above that it's sorted by the server, not matter number or string

**Comment by IceOnFire** [comment]
@kenberkeley Yes you said it twice already, but here we are again. This means that maybe your reply is answering a different question than what is being asked to you.

When a user clicks on the arrows of a sortable column, the query to the server changes and so the server gives new results given that query. We got it. But how does the server know whether it should sort a column if the user is not able to click on any arrows?

No clickable arrows -> No altered query -> no sorted data from server

Please take some time to read and understand our questions. Do you need a screenshot or a live example of the problem we're facing?

**Comment by kenberkeley** [comment]
a screenshot might be better to demostrate

**Comment by kenberkeley** [comment]
![image](https://user-images.githubusercontent.com/13287948/41593529-f43d6bbc-73f2-11e8-8f73-1753ad4ba467.png)

**Comment by IceOnFire** [comment]
Hi @kenberkeley,

Thank you for the screenshot. As you can see, the arrows are set to show up only for numeric columns (User ID and Age), but that's just a coincidence because it would work for string columns too (Username etc.)

I found the solution to our problem: we weren't importing FontAwesome's icons, so that's why we couldn't see any arrows (but we wrongly supposed that it was because of string columns).

So thank you for your feedback, everything works as expected now!

**Comment by kenberkeley** [comment]
I should have guessed fontawesome problem
