### ISSUE TITLE
Can't find module "vue2-datatable" TypeScript !

### ISSUE THREAD

**Issue by AhmedElbatt** [OneWayTech/vue2-datatable#113]
I am newbie to either typescript and Vue.js ; and I am experiencing an issue that related with using the Vue-good-table componant inside a typescript file like this;

import Vue from 'vue'
import Datatable from 'vue2-datatable-component'

TS compiler throws a compile error (Can't find module "vue2-datatable").Can anyone help me please ?

**Comment by kenberkeley** [comment]
`>_ npm i -S vue2-datatable-component`
