### ISSUE TITLE
localStorage is not defined

### ISSUE THREAD

**Issue by Daniyal83** [OneWayTech/vue2-datatable#114]
I'm using it with Nuxt.js. When i'm trying to install it and set up i'm a little confused what should i include:
 include: [
        <path to source directory>, // directory for what?
        /vue2-datatable-component/ // <-- add this!
      ]
i 'm getting an error: localstorage is not defined

**Comment by kenberkeley** [comment]
which file and which line?

**Comment by kenberkeley** [comment]
this component does not support SSR

**Comment by Daniyal83** [comment]
Thanks. Can you suggest any other component like this with SSR?

**Comment by kenberkeley** [comment]
hard to tell... but IMO, table data does not need SEO so that render them only in clients

**Comment by Daniyal83** [comment]
Ok. I'll try to find out the best solution. Thx.
