### ISSUE TITLE
Q: how to use I18N?

### ISSUE THREAD

**Issue by danieltutu** [OneWayTech/vue2-datatable#115]
Currently I cannot use ES6 and I have the following piece of code:

```
const locale = {
  /* HeaderSettings/index.vue */
  'Apply': '应用',
  'Apply and backup settings to local': '应用并保存设置到本地',
  'Clear local settings backup and restore': '清空本地设置并恢复',
  'Using local settings': '正在使用本地设置',

  /* Table/TableBody.vue */
  'No Data': '无数据',

  /* index.vue */
  'Total': '共',
  ',': '项，',

  /* PageSizeSelect.vue */
  'items / page': '项 / 页'
};

Vue.use(Datatable, {locale});
```

When I save and refresh the page, the text of the table is not changed. Am I doing something wrong?

Here is the JSFIDDLE: https://jsfiddle.net/r1gue4en/

**Comment by kenberkeley** [comment]
any error in the console?

**Comment by kenberkeley** [comment]
it could not be possible... why...

**Comment by kenberkeley** [comment]
according to https://github.com/OneWayTech/vue2-datatable/blob/master/src/main.js#L4
it should work

**Comment by danieltutu** [comment]
I read the documentation, please see here the JSFIDDLE https://jsfiddle.net/r1gue4en/

**Comment by kenberkeley** [comment]
![image](https://user-images.githubusercontent.com/13287948/40117543-d498dbd4-5949-11e8-94b6-8c52ab19d6aa.png)

**Comment by kenberkeley** [comment]
https://github.com/OneWayTech/vue2-datatable/blob/master/src/main.js#L12-L14

**Comment by kenberkeley** [comment]
npm: yes
cdn: noop

**Comment by kenberkeley** [comment]
Solution: https://jsfiddle.net/kenberkeley/wfrbuyzz/

**Comment by danieltutu** [comment]
I think it would be a good idea to add this to documentation.

**Comment by kenberkeley** [comment]
I think I should learn the way ElementUI does for i18n. Keep this issue open and I will improve it later
