### ISSUE TITLE
Apply class on some <tr> balise, not on all rows

### ISSUE THREAD

**Issue by ph-freeminds** [OneWayTech/vue2-datatable#118]
Hi,
My issue is about apply 'danger' class on some rows to highlight them.
I tried to use the 'tdComp' option but it adds class on all rows,

I found nothing about it into documentation, can you help me ? Is it possible to do it ?

Thanks

**Comment by kenberkeley** [comment]
in tdComp:

```js
$(this.$el).closest('tr').addClass('danger')
```
