### ISSUE TITLE
Pagination and PageSize

### ISSUE THREAD

**Issue by r9software** [OneWayTech/vue2-datatable#119]
Pagination | Whether to render pagination relevant
I just want to disable "PageSize component" because in a small space the table is overlaping one to the other, I think that having the option to disable pagination and pageSize component is a good change for the Library

![image](https://user-images.githubusercontent.com/4197159/40638525-6d67db54-62d1-11e8-8409-33da93f92acd.png)

**Comment by kenberkeley** [comment]
`:Pagination=false`

**Comment by r9software** [comment]
@kenberkeley  :Pagination=false will disable both page size and pagination, I want to keep pagination but disable page size component

**Comment by kenberkeley** [comment]
Well... how about `$('div[name=PageSizeSelect]').remove()`?

**Comment by r9software** [comment]
well, it can be included also on the configuration of the datatable component, right?

**Comment by kenberkeley** [comment]
use your own fork might be better

**Comment by kenberkeley** [comment]
too many scenarios result in too many config options

**Comment by r9software** [comment]
https://github.com/OneWayTech/vue2-datatable/blob/master/src/index.vue#L13
the usage of a row in the parent is not compatible with the edge case with 1 col
since you are using a default spacing it is not compatible with all the cases
Using 2 rows is better or give the user the option to set that configuration, it is a 3 lines change that improves UX for some cases.

**Comment by r9software** [comment]
also 
$('div[name=PageSizeSelect]').remove() wont work because it is not wrapped in a div PageSizeSelect is a label
https://github.com/OneWayTech/vue2-datatable/blob/master/src/PageSizeSelect.vue#L2

**Comment by kenberkeley** [comment]
😂😂😂

**Comment by r9software** [comment]
After removing the element $('label[name=PageSizeSelect]').parent().remove(); the view is displayed to the left and not centered. @kenberkeley

**Comment by r9software** [comment]
So... nice wrap man! you made it

**Comment by kenberkeley** [comment]
trust me: use your own fork

i am no longer work for OneWay

**Comment by kenberkeley** [comment]
bug reports are welcome but refactor might not...

**Comment by vrajroham** [comment]
@r9software following line will help you to remove/hide parent col.

```javascript
$('label[name=PageSizeSelect]').parent().css({'visibility':'hidden'});
```

**Comment by r9software** [comment]
Hey @kenberkeley  is there a way to force a reload of the table? I want to include a dynamic header value but I have not figure out how

**Comment by kenberkeley** [comment]
how about this...

```js
<datatable v-if="tableVisible" v-bind="tableConfig" />

this.tableVisible = false

// set dynamic values ...

this.$nextTick(() => {
  this.tableVisible = true
})
```
