### ISSUE TITLE
When importing Datatable, Unexpected Token Error?

### ISSUE THREAD

**Issue by robschaap242** [OneWayTech/vue2-datatable#12]
Following the docs, off the bat when I import it I get:

node_modules/vue2-datatable-component/lib/index.vue:1
<template>
^
ParseError: Unexpected token

?

**Comment by kenberkeley** [comment]
Show me your Webpack configuration please.
I guess `vue-loader` or `babel-loader` has excluded `node_modules`.

**Comment by taryamanesh** [comment]
I get the this as well here is the error:

` error  in ./node_modules/vue2-datatable-component/src/index.vue

Syntax Error: Unexpected token (38:59)

  36 |   created () {
  37 |     // init query (make all the properties observable by using `$set`)
> 38 |     const q = { limit: 10, offset: 0, sort: '', order: '', ...this.query }
     |                                                            ^
  39 |     Object.keys(q).forEach(key => { this.$set(this.query, key, q[key]) })
  40 |   },
  41 |   watch: {`

**Comment by kenberkeley** [comment]
@taryamanesh https://github.com/babel/babel-loader/issues/170

**Comment by fnash** [comment]
Thank you @kenberkeley !
Is this the best way to let babel process the Vue plugin?
```javascript
  module: {
    rules: [
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('node_modules/vue2-datatable-component/src'), resolve('test')]
      }
     ]
    }
```

**Comment by kenberkeley** [comment]
I prefer using `/vue2\-datatable\-component/`...

**Comment by kenberkeley** [comment]
This is my conf:

```js
{
  test: /\.js$/,
  loader: 'babel-loader?cacheDirectory',
  include: [
    PATHS.SRC,
    /vue2\-datatable\-component/
  ]
}
```

**Comment by fnash** [comment]
What is PATHS.SRC please?

**Comment by kenberkeley** [comment]
forget about it...

**Comment by allpereira** [comment]
I've been trying I didn't reach the solution. I follow previously solutions, but don't work.


```
ERROR in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vue2-datatable-component/src/index.vue
Module build failed: SyntaxError: Unexpected token (38:59)

  36 |   created () {
  37 |     // init query (make all the properties observable by using `$set`)
> 38 |     const q = { limit: 10, offset: 0, sort: '', order: '', ...this.query }
     |                                                            ^
  39 |     Object.keys(q).forEach(key => { this.$set(this.query, key, q[key]) })
  40 |   },
  41 |   watch: {

 @ ./~/vue2-datatable-component/src/index.vue 8:2-89
 @ ./~/vue2-datatable-component/src/main.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://allpereira.com:8080 webpack/hot/dev-server ./src/main.js
```

The below code is into webpack.config.js  in modules/rules : 

```
              {
                test: /\.jsx?$/,
                exclude: /node_modules/,
                loader: 'babel-loader',
                query: {
                  presets:[ 'es2015', 'react', 'stage-2' ]
                }
              },

              {
                test: /\.js$/,
                loader: 'babel-loader?cacheDirectory',
                include: [
                    /src/,
                  /vue2\-datatable\-component/
                ]
              },
```

: ) Thank you.

**Comment by kenberkeley** [comment]
`test: /\.jsx?$/` and `test: /\.js$/` are duplicates

**Comment by allpereira** [comment]
@kenberkeley, I did this, but dont work yet.

**Comment by kenberkeley** [comment]
```js
{
  test: /\.jsx?$/,
  exclude: /node_modules/,
  loader: 'babel-loader?cacheDirectory',
  query: {
    presets: ['es2015', 'stage-2'] // react is unnecessary
  },
  include: [
    path.join(__dirname, '<path to>/src'),
    /vue2-datatable-component/
  ]
}
```

**Comment by kenberkeley** [comment]
But it's more common to use `.babelrc`:  
```json
{
  "presets": [
    ["env", { "modules": false }],
    "stage-2"
  ],
  "plugins": ["transform-runtime"],
  "comments": false
}
```

**Comment by allpereira** [comment]
@kenberkeley thank you so much! I did solve my problem changing the `.babelrc` file with the code piece that you write before.

**Comment by candradebh** [comment]
I copied the suggestion here.

**Comment by kenberkeley** [comment]
no idea about integrating with laravel...
