### ISSUE TITLE
Allow for sortable column name to be different than field.

### ISSUE THREAD

**Issue by djpate** [OneWayTech/vue2-datatable#121]
I have a json such as this

```
{
  "id": 5,
  "subject": "My Post",
  "author": {
    "id": 10,
    "name": "Chris"
  }
}
```

If I create a two columns for displaying both the id and the name of the author, I will use the field author and then use a custom component to do `value.id` and `value.name`. This works fine for display purposes but if I want to be able to sort on author.id and author.name the sort field will always be `author`.

I can do a PR but I want to make sure you're open to it before I spend the time.

**Comment by kenberkeley** [comment]
you can use your own fork

**Comment by djpate** [comment]
Do you have any interest in adding that to the project itself? my company is not very fond of using personal forks...

**Comment by djpate** [comment]
Gotcha. I believe it's not that uncommon but It's your project! 

Thanks for your response :+1:

**Comment by kenberkeley** [comment]
https://codesandbox.io/s/0o4vmpj99v

**Comment by kenberkeley** [comment]
you are welcome
