### ISSUE TITLE
Failed to mount component: template or render function not defined.

### ISSUE THREAD

**Issue by imadarif** [OneWayTech/vue2-datatable#126]
when i try to use tdComp 

 data() {
        return {
            
            columns: [
                {title: 'Title', field: 'title' },
                {title: 'Description', field: 'description'},
                {title: 'Username', field: 'activityBy'},
                {title: 'Ip Address', field: 'activityIp'},
                {title: 'Activity Date', field: 'activityDate',tdComp: 'CreatetimeTd'}
            ],
            total: 0,
            query:{
                limit: 10,
                offset: 0
            },
            data: [],
            values: {
                skip: 0,
                limit: 50
            },
            xprops: {
                search: ""
            },
            pageSizeOptions: [10, 20, 40, 100]
        }
    },

i got this error 

Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <Anonymous>
       <TableBody> at node_modules/vue2-datatable-component/src/Table/TableBody.vue
         <TableFrame> at node_modules/vue2-datatable-component/src/Table/TableFrame.vue
           <Tbl> at node_modules/vue2-datatable-component/src/Table/index.vue
             <Datatable> at node_modules/vue2-datatable-component/src/index.vue
               <ActivityLog> at src/views/others/activityLog.vue
                 <Head> at src/views/shared/head.vue
                   <App> at src/App.vue
                     <Root>

**Comment by kenberkeley** [comment]
Did you register `CreatetimeTd`?

**Comment by imadarif** [comment]
I fix it by add default

require('./components/Listing.vue').default
Since v13, vue-loader exports the component as the default key, which still works the same when using import, but requires the above when using require

previous: 
// if some dynamic components are used frequently, a better way is to register them globally
export default {
  DisplayRow: require('./nested-DisplayRow'),
  Color: require('./td-Color'),
  CreatetimeTd: require('./td-Createtime'),
  CreatetimeTh: require('./th-Createtime'),
  Email: require('./td-Email'),
  IP: require('./td-IP'),
  Opt: require('./td-Opt'),
  FilterTh: require('./th-Filter')
  // [Vue warn]: Do not use built-in or reserved HTML elements as component id: Filter
  // Filter: require('./th-Filter')
}

fixed:
// if some dynamic components are used frequently, a better way is to register them globally
export default {
  DisplayRow: require('./nested-DisplayRow').default,
  Color: require('./td-Color').default,
  CreatetimeTd: require('./td-Createtime').default,
  CreatetimeTh: require('./th-Createtime').default,
  Email: require('./td-Email').default,
  IP: require('./td-IP').default,
  Opt: require('./td-Opt').default,
  FilterTh: require('./th-Filter').default
  // [Vue warn]: Do not use built-in or reserved HTML elements as component id: Filter
  // Filter: require('./th-Filter')
}


ref: https://forum.vuejs.org/t/solved-using-standalone-version-but-getting-failed-to-mount-component-template-or-render-function-not-defined/19569/2

**Comment by kenberkeley** [comment]
Awesome!
