### ISSUE TITLE
how to jump to specific page

### ISSUE THREAD

**Issue by Lincoln-xzc** [OneWayTech/vue2-datatable#131]
In my case, I need to have an input for users to type a page number to jump to the specific page they want. Does vue2-datatable has this function already? If not, how can I add it? Any suggestions?

**Comment by kenberkeley** [comment]
https://github.com/OneWayTech/vue2-datatable/blob/master/src/Pagination.vue#L63

**Comment by kenberkeley** [comment]
any problem?
