### ISSUE TITLE
Enable Devtools

### ISSUE THREAD

**Issue by palamike** [OneWayTech/vue2-datatable#132]
Hi,

I try to run example and would like to know the data in the component.

However, Devtools has been disabled. I try to change the example.js and lib.js configurations by settings devtools property to true.

then run npm run start or npm run build still can not use devtools.

Any suggestion to enable devtools ?

**Comment by kenberkeley** [comment]
```
$ git clone https://github.com/OneWayTech/vue2-datatable.git
$ cd vue2-datatable/
$ npm i
$ npm start
```

then open http://localhost:4000
