### ISSUE TITLE
Is there any way to attach an onclick handler to a row?

### ISSUE THREAD

**Issue by catcher-in-the-try** [OneWayTech/vue2-datatable#133]
Scenario: The user clicks a table row, and Vue router navigates to another page.

**Comment by kenberkeley** [comment]
Open https://onewaytech.github.io/vue2-datatable/examples/dist/#basic
run the code below in the console:

```js
const vm = this
$('table').on('click', 'tr', function () {
  const idx = $(this).index()
  const row = vm.data[idx]
  window.open(row.xxxURL) ???
})
```

**Comment by catcher-in-the-try** [comment]
@kenberkeley it worked!

**Comment by catcher-in-the-try** [comment]
Actually I keep coming back to this, so perhaps this should be in the documentation (the `index()` method which is not obvious).
