### ISSUE TITLE
Is this project have dependency from JQuery?

### ISSUE THREAD

**Issue by BegeMode** [OneWayTech/vue2-datatable#134]
I have found this dependency in src\HeaderSettings\index.vue:

`mounted () {
    // control dropdown manually (refers to http://jsfiddle.net/rj3k550m/3)
    const $el = $(this.$el)
    $(this.$refs.dropdownBtn).on('click', this.toggle)
    $(document).on('click', e => {
      $(e.target).closest($el).length || $el.removeClass('open')
    })
  },`
Why?
Now, in 2018, this dependency is unnecessary.

**Comment by kenberkeley** [comment]
I am sorry
