### ISSUE TITLE
Highlighting Selected Rows from Selection

### ISSUE THREAD

**Issue by jaira** [OneWayTech/vue2-datatable#14]
Hi @kenberkeley,

Is there a way to configure this datatable to highlight the selected row whenever the checkbox for selection is checked?

BTW, I'm really delighted to find this datatable. Thank you so much for creating this! :)

**Comment by kenberkeley** [comment]
```js
watch: {
  selection (selection) {
    // Using jQuery is more convenient than the data-driven way
  }
}
```
