### ISSUE TITLE
is it possible to have multiple datatable in a single page?

### ISSUE THREAD

**Issue by samiurz** [OneWayTech/vue2-datatable#140]

**Comment by kenberkeley** [comment]
of course, but not recommend

**Comment by kenberkeley** [comment]
wrap datatable's data in an object, i.e. `datatableConfig`

**Comment by samiurz** [comment]
i really need to use multiple datatable in a single page for my information visual representation. How can i achieve that?

**Comment by kenberkeley** [comment]
dive into examples/ and see how i did that

**Comment by samiurz** [comment]
This is my first table: 

`<datatable v-bind="$data">
                                    <table-navigation :selection='selection' :query='query' :createRoute="'Add Company'" :editRoute="'Edit Company'" :deleteUrl="'/api/company/deletetin'">
                                    </table-navigation>
                                </datatable>`

second table?: 

`<datatable v-bind="$datatableConfig">
                                    <table-navigation :selection='selection' :query='query' :createRoute="'Add Company'" :editRoute="'Edit Company'" :deleteUrl="'/api/company/deletetin'">
                                    </table-navigation>
                                </datatable>`

**Comment by kenberkeley** [comment]
```
<datatable v-bind="tblData1" />
<datatable v-bind="tblData2" />

data:() => ({
  tblData1: {...},
  tblData2: {...}
})
```
