### ISSUE TITLE
Customize the checkbox style

### ISSUE THREAD

**Issue by VgSan** [OneWayTech/vue2-datatable#148]
![image](https://user-images.githubusercontent.com/22831769/44910676-bb339700-ad41-11e8-8fc2-ce9b503642ee.png)

**Comment by kenberkeley** [comment]
https://github.com/OneWayTech/vue2-datatable/blob/master/src/Table/MultiSelect.vue

**Comment by VgSan** [comment]
![image](https://user-images.githubusercontent.com/22831769/44910776-1c5b6a80-ad42-11e8-9cc4-3e54a0906ee4.png)
![image](https://user-images.githubusercontent.com/22831769/44910792-29785980-ad42-11e8-87f6-0b8122c24a63.png)
![image](https://user-images.githubusercontent.com/22831769/44910811-3a28cf80-ad42-11e8-8427-0614a05c8c92.png)

**Comment by VgSan** [comment]
Is it possible to do these changes for next release ?

**Comment by kenberkeley** [comment]
use your own fork please

**Comment by kenberkeley** [comment]
under your name, such as @vgsan/vue2-datatable

**Comment by kenberkeley** [comment]
under your name, such as @vgsan/vue2-datatable
