### ISSUE TITLE
Question about relationship object data

### ISSUE THREAD

**Issue by warrence** [OneWayTech/vue2-datatable#15]
Hi, my query data result has another relationship data as below:

```
{
  id,
  username,
  password,
  profile {
     first_name,
     last_name
  }
}
```

I tried to as below but not working

```
{ title: 'First Name', field: 'profile.first_name', sortable: true },
```

Please advise. Thanks.

**Comment by kenberkeley** [comment]
Source: https://github.com/OneWayTech/vue2-datatable/blob/master/src/MainTable/TableBody.vue#L16

**Comment by kenberkeley** [comment]
Advice:

```js
api(this.query).then((rows, total) => {
  this.data = rows.map(row => {
    row.first_name = row.profile.first_name
    row.last_name = row.profile.last_name
  })
  this.total = total
})
```

**Comment by kenberkeley** [comment]
Or using [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy):

```js
api(this.query).then((rows, total) => {
  this.data = rows.map(row => {
    return new Proxy(row, {
      get (obj, prop) {
        return ['first_name', 'last_name'].includes(prop) ? obj.profile[prop] : obj[prop]
      }
    })
  })
  this.total = total
})
```

**Comment by AdrianLungu** [comment]
Hello,

Sorry to comment on a closed thread, just wanted to ask:

Would it be possible to add something such as lodash **_get** ? 

There are use cases where the number of columns is rather big and flattening them could become cumbersome while using _get would allow accessing nested data quite easy.

Thanks!

**Comment by kenberkeley** [comment]
@AdrianLungu could you just elaborate with an example?

**Comment by AdrianLungu** [comment]
Following your previous advice, I've actually found a library called **flat** which helps to flatten very big objects so the whole process doesn't become cumbersome. 

Thanks!

**Comment by kenberkeley** [comment]
@AdrianLungu cool!

**Comment by davidsielert** [comment]
I don't understand here.. the datatables documentation seems to support nested path params, or is this not based upon that library?

**Comment by davidsielert** [comment]
The use case here is that one to many relations just gives numerical indexes and I can't guarantee ordering here..
