### ISSUE TITLE
 Error: Can't resolve '../_mockData' mockdata not found

### ISSUE THREAD

**Issue by JayU9769** [OneWayTech/vue2-datatable#154]
I am using laravel 5.6 + Vue js and i am facing this issue while mounting component and the time of the npm run dev . guyz plz help how can i fix this issue..

this is my component file datatable.vue
--------------------------------------------------
<template>
    <div>
        <code>query: {{ query }}</code>
        <datatable v-bind="$data" />
    </div>
</template>
<script>
    import mockData from '../_mockData';

    export default {
        data: () => ({
            columns: [
                { title: 'User ID', field: 'uid', sortable: true },
                { title: 'Username', field: 'name' },
                { title: 'Age', field: 'age', sortable: true },
                { title: 'Email', field: 'email' },
                { title: 'Country', field: 'country' }
            ],
            data: [],
            total: 0,
            query: {}
        }),
        watch: {
            query: {
                handler (query) {
                    mockData(query).then(({ rows, total }) => {
                        this.data = rows
                        this.total = total
                    })
                },
                deep: true
            }
        }
    }
</script>

-----------------------------

**Comment by kenberkeley** [comment]
`import mockData from '../_mockData/index.js'`
