### ISSUE TITLE
Sorting Issue

### ISSUE THREAD

**Issue by VgSan** [OneWayTech/vue2-datatable#156]
![image](https://user-images.githubusercontent.com/22831769/45091988-af751580-b131-11e8-9464-fc070984d353.png)

Sorting should work like (when CAPS and lower)

![image](https://user-images.githubusercontent.com/22831769/45092059-eb0fdf80-b131-11e8-8a5a-a207c5370fb0.png)

**Comment by kenberkeley** [comment]
sorting is done by the backend
