### ISSUE TITLE
How to deal with super large dataset?

### ISSUE THREAD

**Issue by wangxuesong29** [OneWayTech/vue2-datatable#157]
The issue I have now is I got data with  2 million records in the database, I want to use a table to show them. 

In the very beginning, I simply read data from API (database) and display it, the browser is dead for sure.

How do I deal with this? My alternative way was to send an API request in each pagination, but it will support the filter function.

Do you have any idea?

**Comment by kenberkeley** [comment]
filter the data rows in the backend for sure
