### ISSUE TITLE
In IE it is not working.

### ISSUE THREAD

**Issue by Sakthi002** [OneWayTech/vue2-datatable#159]
![capture](https://user-images.githubusercontent.com/35330401/45746901-ff6bd600-bc21-11e8-9384-deb9ca23d943.PNG)
pageSizeOptions showing error

**Comment by kenberkeley** [comment]
![image](https://user-images.githubusercontent.com/13287948/45747066-592acb00-bc37-11e8-9fbd-c0580eafb7af.png)

**Comment by kenberkeley** [comment]
![image](https://user-images.githubusercontent.com/13287948/45747096-6d6ec800-bc37-11e8-8c3b-db848ccf10af.png)

**Comment by Sakthi002** [comment]
tanq
