### ISSUE TITLE
Omit select checkbox based on criteria

### ISSUE THREAD

**Issue by TheDude70** [OneWayTech/vue2-datatable#16]
Love the ease of adding the select check boxes to a datatable. I do have situations where I would like to have the select check boxes / select all option, except for some. Is there a way to not display the checkbox in specific rows, for example, I may have locked records that I do not want to be selectable, but still need to display?

**Comment by kenberkeley** [comment]
```js
watch: {
  selection (selection) {
    const lockedRecordIds = [1, 2, 3, 4, 5]
    if (selection.find(row => lockedRecordIds.includes(row.id))) {
      selection = selection.filter(row => !lockedRecordIds.includes(row.id))
    }
  }
}
```

**Comment by kenberkeley** [comment]
also using jQuery for aid

**Comment by kenberkeley** [comment]
According to https://github.com/OneWayTech/vue2-datatable/blob/master/src/Table/MultiSelect.vue#L2  
the selector should be `$('input[name=MultiSelect]')`

**Comment by kenberkeley** [comment]
```js
watch: {
  data (data) {
    this.$nextTick(() => { // waiting for DOM render
      const lockedRecordIds = [1, 2, 3, 4, 5]
      const MultiSelects = $(this.$el).find('input[name=MultiSelect]')
      data.forEach((row, idx) => {
        $(MultiSelects[idx + 1]).prop('disabled', lockedRecordIds.includes(row.id))
      })
    })
  }
}
```

**Comment by kenberkeley** [comment]
I would recommend the latter method

**Comment by TheDude70** [comment]
Thanks for the quick response. Have tried something like this:

```
watch: {
        data (data) {
            this.$nextTick(() => {
                const MultiSelects = document.querySelectorAll('input[name=MultiSelect]');
                data.forEach((row, idx) => {
                    if(row.id <= 1) {
                        $(MultiSelects[idx + 1]).remove();
                    }
                })
            });
        },

        selection (selection) {
            if (selection.find(row => row.id <=1)) {
                this.selection = selection.filter(row => row.id > 1)
            }
        },
}
```

First, I'm trying to stay away from having to use jQuery.

Second, what I do not like about this approach is that I must define two watchers to make things 'work'. if there is no watcher for selection, then when clicking the 'toggle all', it would still include the ones I don't want to be selected.

Third, I don't want to have the checkbox show at all, so I need to remove it after it first has been added.

Fourth, with having to filter the `selection` it then unchecks the 'toggle all' checkbox in the header, resulting in not being able to uncheck all the others with a single click. That means I'd have to declare an extra variable to store the filtered selection and leaving the `selection` as is, and that would work by changing my `selection` watcher to:
```
selection (selection) {
                this.selection2 = selection.filter(row => row.id > 1)
        },
```

Feels a little dirty :wink:

Any way to be able to have a closure passed on when `selection` is used to render the check boxes, and also filters the `rows` that are used for the 'toggle all' checkbox?

**Comment by kenberkeley** [comment]
https://onewaytech.github.io/vue2-datatable/doc/#/en/DIY
