### ISSUE TITLE
If field is an object, can't access object value directly

### ISSUE THREAD

**Issue by ignaciogeli** [OneWayTech/vue2-datatable#161]
Hello, and first of all, vue2-datatable its great.
Now....Let's say the employee i am showing in the table has a company. for example:
```
{
	uid: "1"
	mail: "kenneth@oneway.mobi"
	name: "Kenneth Thompson "
	company: {
		cid: "1"
		name: "Oneway"
	}
}
```

Defining my column like: 
```
columns: [
    {
        field: 'company.name'
...
...
```

Does not show anything. 
Regards.

**Comment by kenberkeley** [comment]
does not support nested structure... use `computed` to add `company_name` by yourself
