### ISSUE TITLE
CDN example not working completly

### ISSUE THREAD

**Issue by dxpux** [OneWayTech/vue2-datatable#168]
I found a CDN example at [Getting started](https://onewaytech.github.io/vue2-datatable/doc/#/en/getting-started?id=%E2%8A%99-cdn).
The example not working on sorting and paging.
[codepen](https://codepen.io/dxpux/pen/YBKxEW)

**Comment by kenberkeley** [comment]
Sorting & pagination is done by the backend, not in the frontend
