### ISSUE TITLE
Custom field function?

### ISSUE THREAD

**Issue by mdford** [OneWayTech/vue2-datatable#18]
Hi,

Is there a way to designate a function for a field so that custom formatting can be applied to the rendered cell?  

As an example, say a I have separate columns for firstName and lastName and I want to display in a single column as the full name. Something like:

```
 fullname: function ( data, type, row ) {
     return data +'  '+ row[3];
 }
```

Thanks!

**Comment by kenberkeley** [comment]
https://github.com/OneWayTech/vue2-datatable/issues/15
