### ISSUE TITLE
添加一新行时，td-Opt里面的按钮没有渲染

### ISSUE THREAD

**Issue by easykoala** [OneWayTech/vue2-datatable#181]
this.data.push(row)添加一行时，td-Opt.vue里面的按钮怎么才能渲染？

**Comment by kenberkeley** [comment]
没想到我的项目还有人在用😂

**Comment by easykoala** [comment]
我觉得很不错，加入行内编辑就基本完美了

**Comment by kenberkeley** [comment]
tdComp 直接传入想要渲染的组件吧（不是字符串形式的组件名字哦）

**Comment by easykoala** [comment]
vue2也刚刚接触，增加新行时，不知道如何传入tdComp？请指教

**Comment by kenberkeley** [comment]
例如，
https://github.com/OneWayTech/vue2-datatable/blob/master/examples/src/Advanced/index.vue#L33

tdComp 传入的是 “Email”, 你可以直接 import Email from ... 之后直接 tdComp: Email

**Comment by easykoala** [comment]
import Opt from './comps/td-Opt'
...
         let row = {name: 'new data', age: 36, tdComp: Opt}
         this.data.push(row)
这样子吗？似乎不行也？

**Comment by kenberkeley** [comment]
原来如此，你是没看文档吧。。。这是在 columns 定义的，不是在 data

**Comment by easykoala** [comment]
用的就是advance例子，现在问题是插入一行，那些td_Opt.vue里面的按钮不会出现呀？
columns：
   { title: 'Operation', tdComp: 'Opt', visible: 'true' }

**Comment by kenberkeley** [comment]
w现在就让你直接传 Opt 而不是 ‘Opt’

**Comment by kenberkeley** [comment]
同时是不是漏了 field

**Comment by easykoala** [comment]
这个栏目里面没有field，就是放一堆按钮，比如删除一行等等

**Comment by kenberkeley** [comment]
可以截个图吗？

**Comment by kenberkeley** [comment]
你可以用 Vue Devtools 看看究竟渲染了没有

**Comment by easykoala** [comment]
![图片](https://user-images.githubusercontent.com/3862129/69323516-dad61880-0c81-11ea-8291-198632a90e31.png)

**Comment by kenberkeley** [comment]
请你用 Vue Devtools 检查一下最后一行的组件是否被渲染了，我查看了源码，这肯定是可以渲染的。

**Comment by kenberkeley** [comment]
我在外面，无法用电脑，抱歉

**Comment by easykoala** [comment]
![图片](https://user-images.githubusercontent.com/3862129/69324013-b169bc80-0c82-11ea-8742-3a91013cdfb2.png)
好的，会不会是因为报错了才不能渲染？

**Comment by kenberkeley** [comment]
没错，是的，因为报错了。
Opt 组件渲染的时候报错了，所以就展示不出来了。

**Comment by easykoala** [comment]
好的谢谢，我看看怎么把错误先消灭掉
