### ISSUE TITLE
Can't use "es" locale settings

### ISSUE THREAD

**Issue by EdgarPsda** [OneWayTech/vue2-datatable#183]
Hello,
in my fork I have locale/es.js file, but when I compile my project error shows, this are my configuration.

package.json:
"vue2-datatable-component": "git+https://github.com/EdgarPsda/vue2-datatable.git",

app.js:
import Datatable from "vue2-datatable-component";
import locale from "vue2-datatable-component/locale/zh-cn";

error message:

ERROR in ./resources/client/assets/js/app.js
Module not found: Error: Can't resolve 'vue2-datatable-component/locale/es'
 in ...

**Comment by kenberkeley** [comment]
Reinstall again please

```
npm i -S https://github.com/EdgarPsda/vue2-datatable.git
```

**Comment by EdgarPsda** [comment]
It works, thanks a lot. :)
