### ISSUE TITLE
On row click event

### ISSUE THREAD

**Issue by nurbek-ab** [OneWayTech/vue2-datatable#19]
Is there a way to listen to row click events? I need to change selection prop upon clicking on any row of the table.

**Comment by kenberkeley** [comment]
You can implement it with a `tdComp`:  
```js
mounted () {
  $(this.$el).closest('tr').on('click', <handler>)
}
```

**Comment by medmans** [comment]
hello,

how can i send data for handler?

**Comment by medmans** [comment]
@kenberkeley `this.data` is referenced to component data, but i want to send a date related to the pressed row. Thanks

**Comment by kenberkeley** [comment]
@medmans How about `this.row`?

**Comment by kenberkeley** [comment]
@medmans  https://onewaytech.github.io/vue2-datatable/doc/#/en/details/dynamic-comps?id=%E2%8A%99-tdcomp

**Comment by medmans** [comment]
in my case, i want to navigate from page to another page by clicking under a row.
by adding  `$(this.$el).closest('tr').on('click', <handler>) ` will always handle the row click, so the base page will navigate directely to the second page !

exemple : 
Page 1 : users table 
Page 2 : user's details

on click, i want to navigate from page table to user details.

**Comment by kenberkeley** [comment]
@medmans `this.$router.push` or `window.open`?

**Comment by kenberkeley** [comment]
@medmans or `location.href`...

**Comment by medmans** [comment]
@kenberkeley this.$router.push, i'm using Programmatic Navigation

**Comment by kenberkeley** [comment]
so, what's your problem actually?

**Comment by kenberkeley** [comment]
you wanna pass the row data to the new page?

**Comment by medmans** [comment]
@kenberkeley my problem is the navigation is always handled, event the users page is mounted, the router navigate directely to the second page and i can not get data from selected row

**Comment by kenberkeley** [comment]
so you might need a state management?

**Comment by kenberkeley** [comment]
or else you have to refetch the row data from the server again

**Comment by medmans** [comment]
@kenberkeley yes i need navigation only when row clicked ! without refresh from server, i want to send a column content to router

**Comment by kenberkeley** [comment]
so it's not an issue of this project pal...

**Comment by kenberkeley** [comment]
in my opinion, a nested user's detail would be better than a new page

**Comment by kenberkeley** [comment]
for state management issue, you might find the solution yourself
e.g. localStorage / sessionStorage / global data / Vue mixin / Vue router param - query / ...

**Comment by medmans** [comment]
@kenberkeley i tried to say state mangement of pages no for data ! i'm not able to read the selected row data by using this : 
`$(this.$el).closest('tr').on('click', <handler>)`
the handler is always fired after mouting the page !

**Comment by kenberkeley** [comment]
One possible solution:
```js
$(this.$el).closest('tr').on('click', () => {
  this.$router.push({ path: '/user/detail', query: { rowData: JSON.stringify(this.row) } })
})
```

***

On user's detail page:

```js
created () {
  this.userData = JSON.parse(this.$route.query.rowData)
}
```

**Comment by kenberkeley** [comment]
I reckon that you are a novice to Vue, right?

**Comment by kenberkeley** [comment]
The best way is refetching data from the server, since the real user might click the *refresh* button of the browser

**Comment by kenberkeley** [comment]
```js
$(this.$el).closest('tr').on('click', () => {
  this.$router.push({ path: '/user/detail', params: { uid: this.row.userId } })
})
```

UserDetail.vue
```js
created () {
  xxxApi.getUserDetail({ uid: this.$route.params.uid }).then(userDetail => {
    // deal with the user detail
  })
}
```

**Comment by kenberkeley** [comment]
@medmans  claim `props: ['row']` and then `this.row`

**Comment by kenberkeley** [comment]
https://github.com/OneWayTech/vue2-datatable/blob/master/src/Table/TableBody.vue#L14

**Comment by medmans** [comment]
@kenberkeley you re right, this will be used if i'm using a dynamic component! but in my case i'm using a simple tdComp like this 

`{ title: 'Details', tdComp: 'DetailsChallenge', visible: 'true'  }`

the component is like this:

```
<template>
  <div class="btn-group btn-group-sm">
    <button @click="rowSelect()" class="btn btn-default" title="view details">
      <i class="fa fa-list-ul"></i>
    </button>
  </div>
</template>
<script>
export default {
  name: "DetailsChallenge",
  props: ['row'],
  mounted () {
    
  },
  methods: {
    rowSelect (){
      // i need here to read the selected row data
    }
  }
}
</script>
<style>

</style>
```


i need to read the current row conent to manipulate data and navigate from page to page! i think that the module do not support that

**Comment by kenberkeley** [comment]
```js
<template>
  <div class="btn-group btn-group-sm">
    <button @click="rowSelect()" class="btn btn-default" title="view details">
      <i class="fa fa-list-ul"></i>
    </button>
  </div>
</template>
<script>
export default {
  name: "DetailsChallenge",
  props: ['row'],
  mounted () {
    
  },
  methods: {
    rowSelect (){
      console.log(this.row) // read the selected row data ???
    }
  }
}
</script>
```

**Comment by medmans** [comment]
@kenberkeley it works fine ! i don't understand why i had received and error that the row is undefined !
thanks for your support and sorry if i made you tired.

Thanks again.
