### ISSUE TITLE
Feature request - multiple column sorting

### ISSUE THREAD

**Issue by Klainer** [OneWayTech/vue2-datatable#2]
Hi, thank you for your awsome work! 
I would be nice to hve multiple column sorting possibility incliude query using ctrl / shift + column select.
Thank you!

**Comment by kenberkeley** [comment]
Pardon me for replying so late.
Have you tried [DIY](https://onewaytech.github.io/vue2-datatable/docs/_book/en/DIY.html) ?
I am busy these days and may not be able to implement this feature as soon as possible.

**Comment by kenberkeley** [comment]
I believe the [doc](https://onewaytech.github.io/vue2-datatable/docs/_book/en/detailed/) is abundant for you to comprehend the whole project.

**Comment by Klainer** [comment]
Thanks for response. I will try implement it on my own. Due to very good design / doc  it seems that it would not be difficult.

**Comment by Klainer** [comment]
Hi there is my solution:
HeadSort.vue

```
<template>
  <a href="javascript:;" @click="handleSort" class="p-l-5">
    <i class="fa" :class="[cls, { 'text-muted': !this.order }]"></i>
  </a>
</template>
<script>
/**
 * Sorting arrows inside <th>
 */
export default {
  props: {
    field: { type: String, required: true },
    query: { type: Object, required: true }
  },
  data: () => ({ order: '' }),
  computed: {
    cls () {
      return `fa-sort-${this.order}`.replace(/-$/, '')
    }
  },
  watch: {
    query: {
      handler (query) {
        let obj = query.sort.find(x => x.dataIndx === this.field);
        obj != null && obj != undefined ? this.order = obj.dir :this.order = ""; 
      },
      deep: true,
      immediate: true
    }
  },
  methods: {
    handleSort (event) {
      const { query, order } = this;

      let obj = null;
      let filtered = query.sort.filter(x => x.dataIndx === this.field);

      if(event.shiftKey === false){
        query.sort = filtered;
      }
      
      if(filtered.length > 0){
        obj = filtered[0];
      }

      let isLast = false;
      let dir = "desc";

      if(obj != null && obj != undefined){
          if(obj.dir === 'asc') {
            query.sort.splice(
              query.sort.indexOf(obj), 1
            );
            this.order = "";
            return;
          }
          dir = obj.dir === 'desc' ? 'asc' : 'desc';
      }
      
      let columnSort = { dataIndx: this.field, dir: dir };

      if(obj != null && obj != undefined){
        obj.dataIndx = this.field;
        obj.dir = dir;
      } else {
            query.sort.push(columnSort);
      }

    }
  }
}
</script>
<style>
.p-l-5 {
  padding-left: 5px;
}
</style>

```

And in Index.vue only this change:
```
line 135  const q = { limit: 10, offset: 0, sort: [], ...query } // removed order, sort is array ofobjects
```

**Comment by kenberkeley** [comment]
Why not commit to your forked repo and build the example for preview (using github pages)?
It may help others and you will be a time saver.
Thanks for your contribution!

**Comment by Klainer** [comment]
You have right, soon I will certainly do it. I have plan to upgrade column filtering schema, to able filtering date ranges, number ranges, etc.. after tahat i will update my fork.

**Comment by kenberkeley** [comment]
The purpose of building this project is just providing basic features and DIY-friendly to developers.
In other words, it does not aim to be a large project which has various features but accompanies with complexity.
Thus, I prefer `fork` or independent `branch`es rather then `merge`.

**Comment by kenberkeley** [comment]
btw, thx for ur attention.
