### ISSUE TITLE
vue build无法使用

### ISSUE THREAD

**Issue by asins** [OneWayTech/vue2-datatable#20]
使用`npm run build:lib`时提示vue-cli中去除了build功能，需要使用Poi工具，

但我在使用Poi工具构建时(poi build --config build/lib.js --prod)提示编译错误，看不到具体的错误信息

```
Conflict: Multiple assets emit to the same filename min.js
```

vue-cli V2.9.1

**Comment by kenberkeley** [comment]
https://github.com/OneWayTech/vue2-datatable/commit/4183240f2c9f5b4504de2c7607ca4884b9e57103

**Comment by kenberkeley** [comment]
重新安装依赖吧：`cnpm i -D vue-cli@2.8.2`

**Comment by asins** [comment]
强制使用 vue-cli V2.8.2版可以解决问题，但看vue官方是想转用poi的。

**Comment by kenberkeley** [comment]
别管它。。。
