### ISSUE TITLE
固定header或列时设计改进建议

### ISSUE THREAD

**Issue by asins** [OneWayTech/vue2-datatable#22]
1. 滚动时多滚动条问题

刚在看`index.vue`中SCROLLBAR_WIDTH变量时了解你的组件隐藏滚动条是通过margin负值实现的，但由于我的Mac中将滚动条显示设置为“滚动时”，
![image](https://user-images.githubusercontent.com/898354/31332635-b3d579e8-ad19-11e7-9402-aa9547d3cfc5.png)
这让margin+overflow:hidden起不到作用，如下截图，效果上不如意噢。

![image](https://user-images.githubusercontent.com/898354/31332558-6a0aa2fc-ad19-11e7-822a-ec796171524d.png)

设计上将`TableHeaderWrapper`、`TableFooterWrapper`设置为`overflow:hidden;`为佳，其它的一小调整也不多。

2. 左右滚动浮动列会显示抖动问题

这是由于你实现固定使用的是`position: absolute;`，建议修改成相对限宽后的容器做定位，这样创建出来后就无需修改了。

**Comment by kenberkeley** [comment]
欢迎 PR 噢！！！

**Comment by kenberkeley** [comment]
主要是最近一直没时间重构，否则的确应该按照 Element 那样实现比较好

**Comment by MichealYang1001** [comment]
![image](https://user-images.githubusercontent.com/12510125/33877546-ad38fc14-df63-11e7-95d5-8f2dfd2d1fda.png)
![image](https://user-images.githubusercontent.com/12510125/33877566-c3564592-df63-11e7-893e-bc0baf624725.png)
引入项目的时候报了这个错，不知道怎么改

**Comment by kenberkeley** [comment]
@MichealYang1001 
https://github.com/OneWayTech/vue2-datatable/issues/45

**Comment by MichealYang1001** [comment]
import Datatable from '../../'  看代码不明白这个地方，引用的是哪个文件夹啊

**Comment by kenberkeley** [comment]
我不是特别欢迎你随便挑一个 issue，然后在下面不断问一些与当前 issue 不相关的，常识性的，或者前人已经问过的问题
