### ISSUE TITLE
is any searchable function？

### ISSUE THREAD

**Issue by ddai043** [OneWayTech/vue2-datatable#23]
please add Fuzzy search function ，I very need it

**Comment by kenberkeley** [comment]
https://github.com/OneWayTech/vue2-datatable/blob/master/examples/src/Advanced/comps/th-Filter.vue

**Comment by kenberkeley** [comment]
any more questions?

**Comment by hhsadiq** [comment]
Can I look some online example of search feature?

Is there search option is this example? https://onewaytech.github.io/vue2-datatable/examples/dist/#advanced

**Comment by kenberkeley** [comment]
@hhsadiq 
![image](https://user-images.githubusercontent.com/13287948/37771089-81b9fa32-2e11-11e8-93fb-0430bb22b978.png)

**Comment by hhsadiq** [comment]
Oh, I got it. I was looking the search bar somewhere in UI. But filter sign also makes sense, although couldn't guess at first glance. Thanks for helping out 👍
