### ISSUE TITLE
Lower library dependencies on global libraries.

### ISSUE THREAD

**Issue by fimdomeio** [OneWayTech/vue2-datatable#24]
I think it's a bit overwhelming that this library depends on having jquery (as a global) and the bootstrap scripts.
As far as I see the scripts part look like they could be easily replaced in native vue code.

My current projects use parts of the bootstrap library (loaded as needed per component) no jquery so I might try a to fork this project and remove those dependencies. Let me know if you would be interested in this developments

**Comment by kenberkeley** [comment]
sounds interesting, i would like to try

**Comment by thiner** [comment]
Agree, I found the only usage of jquery in example is th-filter, which is totally unnecessary in my opinion.

**Comment by kenberkeley** [comment]
P.S. BootStrap and Font Awesome can be replaced with other popular libraries.
(It seems to me that you just have to replace some classes / styles)

> excerpted from https://onewaytech.github.io/vue2-datatable/doc/#/en
