### ISSUE TITLE
Complication Issues

### ISSUE THREAD

**Issue by keyurptl** [OneWayTech/vue2-datatable#27]
Hey Thanks for such great plugin.

But when I load dependency with NPM  and tried to install but getting below error.
https://www.screencast.com/t/EoaolScJs8A

Can you please help me on this.

**Comment by kenberkeley** [comment]
https://babeljs.io/docs/plugins/transform-object-rest-spread/

**Comment by keyurptl** [comment]
Thanks for your response.
Sorry not getting for what you provided this link.

**Comment by kenberkeley** [comment]
https://github.com/babel/babel-loader/issues/170

**Comment by keyurptl** [comment]
Sorry Let me clear you what I did and what I want. 

Actually I want use datatable in my component. to display data and Also need pagination and sorting,searching etc.

And I am using Laravel + Vue js. 

What I did till now is.

Following this link https://onewaytech.github.io/vue2-datatable/doc/#/en/getting-started

1) npm i -S vue2-datatable-component [Install plugin] 

Add below code in app.js file 
import Datatable from 'vue2-datatable-component';
Vue.use(Datatable); 

After compile this I am getting error like below when tried to use npm run dev. 
https://www.screencast.com/t/EoaolScJs8A

So can you please help me on this.

**Comment by kenberkeley** [comment]
Excuse me for taking a nap...
Well, frankly speaking, this issue is about your Webpack + Babel configuration, not the problem of this repo

**Comment by kenberkeley** [comment]
The links I pasted above are the solutions to this

**Comment by kenberkeley** [comment]
You might need to learn more about these knowledge to solve your issues

**Comment by keyurptl** [comment]
Thing is that issues is not web-pack related . It showing me error in  
./node_modules/vue2-datatable-component/src/index.vue   

Means in this file index.vue of your package.
https://www.screencast.com/t/gRujpqUp6

I am asking for this one.

**Comment by kenberkeley** [comment]
Why not take a look at https://github.com/babel/babel-loader/issues/170 ?
