### ISSUE TITLE
tdComp of a table inside a nested component is not loading

### ISSUE THREAD

**Issue by jaira** [OneWayTech/vue2-datatable#28]
I have used two datatable. From the Parent table I use the nested component. Inside the nested component is another datatable with column using tdComp. For some reasons, I can't load the content of the column of the inner datatable. I have checked the Vue console, the dynamic component for the tdcomp table is not included to the tree.

**Comment by kenberkeley** [comment]
May I eye on your code?

**Comment by jaira** [comment]
This is my parent table code:
`<template>
<section class="content">
  <div>
    <datatable v-bind="$data">
      <button class="btn btn-default" @click="addItem()" title="Add Item">
      <i class="fa fa-plus" aria-hidden="true"></i>
      </button>
      <button class="btn btn-default" @click="editItem()" title="Edit Item">
      <i class="fa fa-pencil" aria-hidden="true"></i>
      </button>
      <button class="btn btn-default" @click="deleteItem()" title="Delete Item">
      <i class="fa fa-trash" aria-hidden="true"></i>
      </button>
    </datatable>
  </div>
</section>
</template>

<script>
import queryFilter from '../../datatable/query-filter'
import ItemDAO from '../../../database/ItemDAO'
import components from '../../datatable/'
import { EventBus } from '../../../eventbus'
import toastr from 'toastr'

export default {
  components,
  name: 'ItemTable',
  data () {
    return {
      businessId: window.localStorage.getItem('selBusinessId'),
      HeaderSettings: false,
      supportBackup: false,
      supportNested: true,
      tblClass: 'table-bordered',
      tblStyle: 'color: #1A2226',
      columns: [
        {
          title: 'Code',
          thComp: 'FilterTh',
          field: 'code'
        },
        {
          title: 'Name',
          field: 'name',
          thComp: 'FilterTh',
          sort: true
        },
        {
          title: 'Description',
          field: 'description'
        },
        {
          title: 'UOM',
          field: 'uom'
        },
        {
          title: 'Total Amount',
          field: 'totalAmount',
          sort: true
        },
        {
          title: 'Packages',
          tdComp: 'ItemPackages'
        },
        {
          title: 'Supplies',
          tdComp: 'ItemSupplies'
        }
      ],
      data: [],
      total: 0,
      selection: [],
      query: {},
      fieldCols: ['code', 'name', 'description', 'uom', 'totalAmount', 'packages', 'supplies'],
      items: []
    }
  },

  mounted () {
    let vm = this

    this.$bindAsArray('items', ItemDAO.Item.getItemListByBusinessId(vm.businessId), null, function () {
      vm.handleQueryChange()
    })

    EventBus.$on('onAddItemFinish', function () {
      vm.handleQueryChange()
    })

    EventBus.$on('onAddItemSupplyFinish', function () {
      vm.handleQueryChange()
    })

    EventBus.$on('onEditItemFinish', function () {
      vm.handleQueryChange()
    })
  },

  methods: {
    handleQueryChange () {
      queryFilter(this.query, this.items, this.fieldCols).then(({
        rows,
        total
      }) => {
        this.data = rows
        this.total = total
      })
    },

    getSelectedIds () {
      let selectedIds = this.selection.map(function (currentValue) {
        return currentValue['.key']
      })
      return selectedIds
    },

    addItem () {
      EventBus.$emit('onAddItem')
    },

    editItem () {
      let selectedIds = this.getSelectedIds()
      if (selectedIds.length === 0) {
        toastr.warning('Please select an item from the table to edit', 'Warning')
      } else if (selectedIds.length > 1) {
        toastr.warning('You can only edit 1 item from the table', 'Warning')
      } else {
        EventBus.$emit('onEditItem', this.getSelectedIds())
      }
    },

    deleteItem () {
      let selectedIds = this.getSelectedIds()
      if (selectedIds.length === 0) {
        toastr.warning('Please select at least one item from the table to delete', 'Warning')
      } else {
        EventBus.$emit('onDeleteItem', this.getSelectedIds())
      }
    }
  },

  watch: {
    query: {
      handler (query) {
        this.handleQueryChange()
      },
      deep: true
    },
    items: {
      handler (query) {
        this.handleQueryChange()
      },
      deep: true
    }
  }
}
</script>

<style>
</style>
`

**Comment by jaira** [comment]
https://codeshare.io/2KoeME

**Comment by kenberkeley** [comment]
Try registering the tdComp globally

**Comment by jaira** [comment]
When you say registering the tdComp globally, do you mean putting the tdComp to the index.js file? just like this:


export default {
  ItemSupplies: require('./items/td-itemSupplies'),
  ItemPackages: require('./items/td-itemPackages'),
  ItemQuantity: require('./items/td-itemquantity'),
  DisplaySuppliesRow: require('./items/supply-DisplayRow'),
  DisplayPackagesRow: require('./items/package-DisplayRow'),
  PCContentLink: require('./productComposition/td-contentLink'),
  PCQuantity: require('./productComposition/td-compositionQuantity'),
  PGContentLink: require('./productGroup/td-contentLink'),
  MbiCount: require('./beginninginventory/td-mbicount'),
  BiSpoilageCount: require('./beginninginventory/td-bispoilage'),
  BiLostCount: require('./beginninginventory/td-bilost'),
  BiNotesCount: require('./beginninginventory/td-binotes'),
  DisplayDate: require('./td-displaydate'),
  DisplayDecimalNumber: require('./td-displayDecimalNumber'),
  DisplayPackaging: require('./td-displayPackaging'),
  FilterTh: require('./th-Filter'),
  eiLost: require('./endinginventory/td-eilost'),
  eiCount: require('./endinginventory/td-eicount'),
  eiSpoilage: require('./endinginventory/td-eispoilage'),
  eiNotes: require('./endinginventory/td-einotes'),

  SPLink: require('./salableproduct/td-productLink'),
  SPCategoryComposition: require('./salableproduct/td-categoryComposition'),
  SPAvailabilityPeriod: require('./salableproduct/td-availabilityPeriod'),

  PromoPeriod: require('./promo/td-promoPeriod')
}

**Comment by kenberkeley** [comment]
https://vuejs.org/v2/api/#Vue-component

**Comment by jaira** [comment]
How do you do that using webpack? (sorry newbie here. T_T)

**Comment by kenberkeley** [comment]
P.S. be aware of the namespace issue

**Comment by kenberkeley** [comment]
```js
import Vue from 'vue'

Vue.component('ItemSupplies', require('./items/td-itemSupplies'))
Vue.component('ItemPackages', require('./items/td-itemPackages'))
...
```

**Comment by kenberkeley** [comment]
If the problem was solved, don't forget to close this issue

**Comment by jaira** [comment]
It works!! Thank you so much!! :D
