### ISSUE TITLE
Search boxes in the demos are broken

### ISSUE THREAD

**Issue by bsamadi** [OneWayTech/vue2-datatable#29]
Instead of the search box, I only see:
`query: { "limit": 10, "offset": 0, "sort": "", "order": "" }`

**Comment by kenberkeley** [comment]
https://github.com/OneWayTech/vue2-datatable/blob/master/src/main.js#L7

**Comment by kenberkeley** [comment]
any errors in console?

**Comment by bsamadi** [comment]
I see this:
https://pasteboard.co/GQhyD1H.png
on the demo page:
https://onewaytech.github.io/vue2-datatable/examples/dist/

There is no related error in the console (only one regarding favicon.ico). It seems to me that <code> is  just displayed and not functional.

**Comment by kenberkeley** [comment]
Excuse me for replying so late... God damn Great Firewall...
Well, this demo is meant to display `query`

**Comment by kenberkeley** [comment]
![image](https://user-images.githubusercontent.com/13287948/31999678-c9319a96-b959-11e7-8b1e-f962351decea.png)
