### ISSUE TITLE
Error in render: "TypeError: _vm.$i18nForDatatable is not a function"

### ISSUE THREAD

**Issue by bsamadi** [OneWayTech/vue2-datatable#30]
It seems that $i18nForDatatable is not defined.

**Comment by kenberkeley** [comment]
https://github.com/OneWayTech/vue2-datatable/blob/master/src/main.js#L7

**Comment by bsamadi** [comment]
I am using Vue js and webpack. My code wasn't able to get this definition on line 7 of main.js. When I added this line to my own code, it complained what "locale" was. I then used this line:
Vue.prototype.$i18nForDatatable = srcTxt => srcTxt

**Comment by kenberkeley** [comment]
Sorry for replying so late (cursing Chinese Great Firewall)
Did you find the solution?

**Comment by paolog22** [comment]
any solution for this ?

**Comment by kenberkeley** [comment]
@paolog22 i've got no idea...

**Comment by kenberkeley** [comment]
could you tell me your Webpack version? 1.x or 2.x?

**Comment by kenberkeley** [comment]
how about:

```js
import Vue from 'vue'
import Datatable from 'vue2-datatable-component/src/main'

Vue.use(Datatable)
```

**Comment by kenberkeley** [comment]
@bsamadi I need your help. May I have your screenshots of code?

**Comment by kenberkeley** [comment]
I need to figure out what causes the problem on earth

**Comment by paolog22** [comment]
@kenberkeley i am using webpack 2

**Comment by kenberkeley** [comment]
@paolog22 have you tried https://github.com/OneWayTech/vue2-datatable/issues/30#issuecomment-346539652?

**Comment by paolog22** [comment]
yes.. same error as this

**Comment by kenberkeley** [comment]
is it alright that you create a repo for me to debug?

**Comment by kenberkeley** [comment]
technically speaking, is for reproducation

**Comment by paolog22** [comment]
implemented successfully! thanks :)

**Comment by kenberkeley** [comment]
？？？。。。

**Comment by paolog22** [comment]
you're right i made a mistake at initializing.. now i am looking for how to render row data with custom html.

**Comment by Defcoun** [comment]
sorry, but i have this mistake ($i18nForDatatable is not defined) too

> [Vue warn]: Property or method "$i18nForDatatable" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.
> found in
> ---> <Datatable> at node_modules/vue2-datatable-component/src/index.vue
       <Pages/index.vue> at pages/index.vue
         <Nuxt> at .nuxt/components/nuxt.vue
           <Default> at layouts/default.vue
             <Root>

//nuxt.config.js
```
build: {
    vendor: [
     ...
      'vue2-datatable-component'
    ],
  },
```

**Comment by kenberkeley** [comment]
@Defcoun You have to register it globally, not locally
