### ISSUE TITLE
How to Implement This with Laravel 

### ISSUE THREAD

**Issue by keyurptl** [OneWayTech/vue2-datatable#32]
Thanks for such great plugin.

My query is how can i we implement  this with Laravel latest version. and I want my all data on pagination using Ajax call and Also each filter should be work with Ajax call. 

Can you please help me how can I use this great plugin with Laravel + Ajax.
Thanks in Advance.

**Comment by kenberkeley** [comment]
Have you read the doc?

**Comment by kenberkeley** [comment]
Hello?
If there is no more question, please close this issue.
BTW, I am not familiar with Laravel...
And I believe that the doc should help.

**Comment by keyurptl** [comment]
Okay Thanks. Let me close this issues for now.

**Comment by rebz** [comment]
I am using this component and had to do the same. I have a page that makes an ajax call to load a list of events. I have a UI Store with two states defined as "filters" and "activeFilters". I have a UI Store Getter called "eventQuery" that actively listens for changes in "activeFilters" and builds out a get string. I have a watcher on the main parent component (which does all the initial dispatches of grabbing data) that listens for changes to "eventQuery" and will execute a new event data dispatch while passing through the eventQuery string.

The above method assumes you're using a state management plugin such as Vuex. I hope this info helps.
