### ISSUE TITLE
Mapping extra properties to tdComp's

### ISSUE THREAD

**Issue by bahrigencsoy** [OneWayTech/vue2-datatable#33]
We need to write simple datatable wrapper components like the one below in order to supply them as `tdComp` values:

```javascript
<template>
    <user :username="value"></user>
</template>
<script>
    import User from '../../User.vue';

    export default {
        props: ['value'],
        components: {
            User
        }
    }
</script>
```

If only some there was a mechanism like defining a property mapping to the `tdComp`, maybe something like:

```javascript
{title: 'User', field: 'creatorUserName', tdComp:'User', propertyMap: {'username': value}}
```

Or I am just missing an easier approach.

**Comment by kenberkeley** [comment]
`$props.row` should help

**Comment by bahrigencsoy** [comment]
Thanks for the ultra-fast reply :)

I might not have not understood your reply, or did not make myself clear.

The thing is, the simple component above works, but it is just a wrapper for `tdComp`->`User` component. It just supplies the `'value'` property of itself as the `username` property of the `User` component.

I really could not understand how the `$props.row` would prevent writing a wrapper component, without rewriting the `User` component.

**Comment by kenberkeley** [comment]
tdComp provideds `props`: `row` / `field` / `value` / ...

**Comment by kenberkeley** [comment]
`this.row.username` is as same as `this.value` if `field: 'username'`

**Comment by bahrigencsoy** [comment]
Wrapper components then it is.
