### ISSUE TITLE
'javascript:;' in anchor links breaks Content-Security-Policy

### ISSUE THREAD

**Issue by bahrigencsoy** [OneWayTech/vue2-datatable#34]
There are several anchor links like:
```html
<a href="javascript:;">
```
Which breaks content security policy.

**Comment by kenberkeley** [comment]
What's your suggestion?

**Comment by kenberkeley** [comment]
Oh, I see your PR now

**Comment by kenberkeley** [comment]
The use of `.stop` confused me, could you explain a lot more?
