### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by johncarlpinca** [OneWayTech/vue2-datatable#36]
Hi! I have problem on pagination. My scenario is I put input text on tdComp then fillup it until row 10, then on the page 2, the whole row copies the value of page 1 and vice versa. My code on the tdComp is here.

```html
<template>
  <div>
    <input name="quantity" type="number" class="form-control quantity" min="1" v-model="quantity" @keyup="onFieldEdit()" step="0.01">
  </div>
</template>

<script>
import { EventBus } from '../../../eventbus.js'

export default {
  props: ['row', 'key'],

  data () {
    return {
      quantity: 1
    }
  },

  mounted () {
    EventBus.$emit('onCompositionValueChange', [this.row['key'], this.quantity])
  },

  methods: {
    onFieldEdit () {
      EventBus.$emit('onCompositionValueChange', [this.row['key'], this.quantity])
    }
  }
}
</script>
```

**Comment by kenberkeley** [comment]
This issue might be the virtual DOM reuse strategy. Here is a possible solution:
```js
methods: {
  fetchList () {
    whateverApi(this.query).then(rows => {
        this.data = []
        this.$nextTick(() => {
          this.data = rows
        })
    })
  }
}
```

**Comment by johncarlpinca** [comment]
Below is how I fetch my list. When I used the code that you said, it doesn't take affect and is still copying value of the next page and vice versa. 

handleQueryChange () {
      queryFilter(this.query, this.compositions, this.fieldCols).then(({
        rows,
        total
      }) => {
        this.data = rows
        this.total = total
      })
 },

**Comment by kenberkeley** [comment]
It seems that `$data.quantity ` is constant

**Comment by kenberkeley** [comment]
Moreover, `props` to tdComp do not include `key`

**Comment by kenberkeley** [comment]
The most frequently used `props` of tdComp are: `row / field / value`

**Comment by kenberkeley** [comment]
I have no idea of your scenario so that I might not be able to help.
