### ISSUE TITLE
Pagination not reducing table content

### ISSUE THREAD

**Issue by byteworksng** [OneWayTech/vue2-datatable#37]
I'm unable to get pagination working. the docs don't explain much to my understanding. 
I have datatables loaded as per documentation. using the advanced code example.
Now footer appears to have pagination displayed and it responds to page select. However, the data on the table does not. I have 31 rows on the table, after switching page select to 5, table doesn't get limited to 5 rows. 

i'm using Vue 2.5.3
vue2-datatable 2.1.18

**Comment by kenberkeley** [comment]
screenshot？

**Comment by kenberkeley** [comment]
rows displayed are only according to `data`

**Comment by byteworksng** [comment]
![screen shot 2017-11-16 at 4 55 41 pm](https://user-images.githubusercontent.com/6043931/32901039-2206701e-caef-11e7-8f93-9f57dac470d7.png)

**Comment by kenberkeley** [comment]
`query.limit` is 5 does not mean `this.data.length` is 5

**Comment by kenberkeley** [comment]
you have to control `this.data` to display

**Comment by byteworksng** [comment]
as seen on the screenshot i'm expecting the table data displayed to be reduced to 5 per page.. but it just stays the same.. what do i need to do to achieve the desired effect as displayed in the example

**Comment by kenberkeley** [comment]
your backend API should return 5 rows according to `query.limit === 5`

**Comment by byteworksng** [comment]
ooh i need to do another server query for the pagination to work?

**Comment by kenberkeley** [comment]
if API outputs all the rows, you have to control the display yourself.
e.g.

```js
this.data = rows.slice(this.query.offset, this.query.offset + this.query.limit)
```

**Comment by byteworksng** [comment]
i thought like datatables.net this is meant to be an option. that is.. once the data is pulled from the server, the table can limit its display

**Comment by kenberkeley** [comment]
noop buddy... it's different

**Comment by kenberkeley** [comment]
if there are 10000000000+ rows, your page stucks!

**Comment by byteworksng** [comment]
so how do i deal with page changes using this approach.. its not clear to me how to customize the behavior and positioning of the elements... going by your example. i already limit returned rows to 100 from the server.. i just want the pagination to split them as needed..

**Comment by kenberkeley** [comment]
that is a front-end pagination... not a common one...

**Comment by kenberkeley** [comment]
as I said, split it your self:

```js
this.data = rows.slice(this.query.offset, this.query.offset + this.query.limit)
```

**Comment by kenberkeley** [comment]
also: `this.query.total = 100`

**Comment by byteworksng** [comment]
ok

**Comment by kenberkeley** [comment]
your scenario is so strange, lol

**Comment by byteworksng** [comment]
maybe id raise a new issue about how to reposition the elements.. e.g remove page-select from the footer and on to the top. also how to change the icon fonts used for sorting... looks like i have to rewrite the index of the datatable just to achive this

**Comment by byteworksng** [comment]
Thanks for the help..

**Comment by kenberkeley** [comment]
you're welcome to DIY
