### ISSUE TITLE
how to reposition the elements in vue2-datatable

### ISSUE THREAD

**Issue by byteworksng** [OneWayTech/vue2-datatable#38]
![screen shot 2017-11-16 at 5 19 48 pm](https://user-images.githubusercontent.com/6043931/32902346-70a62bee-caf2-11e7-9951-8e3e75288865.png)
Here is a screenshot of the table i hope to achieve. using vue2-datatable as a requirement all tables must be presented exactly the same way. this used datatable.net but unfortunately vue doesn't play well with it. so i discovered your system and now, i want to achieve this look.. but not seeing slots where i can include the elements without having to rewrite the index of this datatable component. which seems like a rather messy approach to me.. 

How is this expected to be handled. thanks

**Comment by kenberkeley** [comment]
no other ways, you have to move https://github.com/OneWayTech/vue2-datatable/blob/master/src/index.vue#L17 to L4

**Comment by kenberkeley** [comment]
i got to sleep, it late night now in China, good night bro

**Comment by byteworksng** [comment]
Cheers

**Comment by byteworksng** [comment]
Maybe using named slots.. can be a good way to intoduce this customization behavior..

**Comment by kenberkeley** [comment]
pardon me for not meeting everyone's appetite
https://onewaytech.github.io/vue2-datatable/doc/#/en/DIY
