### ISSUE TITLE
not compatible with VueI18n

### ISSUE THREAD

**Issue by fatb0000** [OneWayTech/vue2-datatable#4]
when I use both kazupon/vue-i18n and vue2-datatable. It got conflict and shown  Error in render function: "TypeError: _vm.$i18n is not a function".
I rename $i18n -> $i18n2 in index.js and index.vue in vue2-datatable, it is working fine.

**Comment by kenberkeley** [comment]
well, it's a coincidence...i will rename it in next version

**Comment by kenberkeley** [comment]
@fatb0000 v1.1.9 is for you!

**Comment by fatb0000** [comment]
thanks!
