### ISSUE TITLE
ES6 有問題

### ISSUE THREAD

**Issue by malcolmjerry** [OneWayTech/vue2-datatable#40]
vue2-datatable/examples/src/Advanced/comps/

這些組件在 index.js 裡 require 時要加 .default,  因為ES6 的 babel 修正了這種用法. 

如下: 

export default {
  DisplayRow: require('./nested-DisplayRow').default,
  Color: require('./td-Color').default,
  CreatetimeTd: require('./td-Createtime').default,
  CreatetimeTh: require('./th-Createtime').default,
  Email: require('./td-Email').default,
  IP: require('./td-IP').default,
  Opt: require('./td-Opt').default,
  FilterTh: require('./th-Filter').default
  // [Vue warn]: Do not use built-in or reserved HTML elements as component id: Filter
  // Filter: require('./th-Filter')
}

**Comment by kenberkeley** [comment]
这仅限于 js 文件而已
