### ISSUE TITLE
Custom row

### ISSUE THREAD

**Issue by paolog22** [OneWayTech/vue2-datatable#41]
how to add custom row for the data? 
thanks

**Comment by kenberkeley** [comment]
`this.data.push(<custom row>)`

**Comment by paolog22** [comment]
thanks for the quick response, can you please elaborate? thanks
can i use this from Parent component to child component which has the datatable ?

**Comment by kenberkeley** [comment]
excuse me for the late replay (just had a meeting)...
I need to learn about your scenario to give advice

**Comment by paolog22** [comment]
thanks you so much :)

**Comment by kenberkeley** [comment]
so, what function you want to implement?

**Comment by kenberkeley** [comment]
I have no idea of `from parent component to child component` which you mentioned above

**Comment by paolog22** [comment]
can i use slot-scope for the row to be custom render ?

**Comment by kenberkeley** [comment]
noop... use [dynamic components](https://onewaytech.github.io/vue2-datatable/doc/#/en/details/dynamic-comps) instead

**Comment by paolog22** [comment]
@kenberkeley thanks ,, sorry i am new to vue hooping to see live example thanks :)

**Comment by kenberkeley** [comment]
https://onewaytech.github.io/vue2-datatable/examples/dist/

**Comment by paolog22** [comment]
@kenberkeley  you need to review your code sir and the documentation.. 
`$i18nForDatatable` <- this is not declared  
thanks

**Comment by kenberkeley** [comment]
I can't reproduce this problem

**Comment by paolog22** [comment]
![image](https://user-images.githubusercontent.com/12680745/33160844-96927d04-d05a-11e7-834e-20d263900bb8.png)
![image](https://user-images.githubusercontent.com/12680745/33160856-b11f127c-d05a-11e7-9a75-877a8d746dd3.png)

@kenberkeley 
maybe you refer to this images. 
hope you find this helpful thanks

**Comment by kenberkeley** [comment]
take a look at https://github.com/OneWayTech/vue2-datatable/blob/master/examples/src/Advanced/index.vue#L15

**Comment by kenberkeley** [comment]
why did you import `Datatable` instead?

**Comment by kenberkeley** [comment]
did you really have the reason for import the whole `Datatable` here?

**Comment by kenberkeley** [comment]
according to the [doc](https://onewaytech.github.io/vue2-datatable/doc/#/en/getting-started), you have to register the `Datatable` globally

**Comment by kenberkeley** [comment]
for novice, I would usually suggest using http://element.eleme.io/#/en-US/component/table instead.

**Comment by kenberkeley** [comment]
if there are no more questions, close this issue please
