### ISSUE TITLE
Doesn't compatible with UglifyJs?

### ISSUE THREAD

**Issue by thiner** [OneWayTech/vue2-datatable#42]
ERROR in static/js/vendor.a06c4cf127ec568bec06.js from UglifyJs
Unexpected token: punc (() [./node_modules/vue2-datatable-component/src/_mixins/props.js:19,0][static/js/vendor.a06c4cf127ec568bec06.js:5041,7]

**Comment by kenberkeley** [comment]
https://onewaytech.github.io/vue2-datatable/doc/#/en/getting-started
