### ISSUE TITLE
detect-scrollbar-width problems

### ISSUE THREAD

**Issue by somazx** [OneWayTech/vue2-datatable#43]
I'm attempting to use this component but I'm getting the following error once I add import the module.

`Cannot read property 'appendChild' of null`

```
// Refers to https://davidwalsh.name/detect-scrollbar-width
const div = document.createElement('div')

div.style.width = '100px'
div.style.height = '100px'
div.style.overflow = 'scroll'
div.style.position = 'absolute'
div.style.top = '-9999px'

document.body.appendChild(div) /* <---- ERROR IS THIS LINE */

const SCROLLBAR_WIDTH = div.offsetWidth - div.clientWidth
```

My guess is that this is running before document has loaded or body doesn't exist at this stage? But why should it exist at the point of import?

I'm using this with default Rails 5.1 + Vue/webpacker setup.

**Comment by kenberkeley** [comment]
Excuse me for the late reply.
Take a look at https://github.com/OneWayTech/vue2-datatable/blob/master/examples/dist/index.html#L15
You will see that the script is placed before the end of body

**Comment by kenberkeley** [comment]
If you place your scripts within `<head>`, without doubt that `document.body` is `null`

**Comment by kenberkeley** [comment]
Or, you can mount the Vue instance to the DOM after `document.ready`:

```js
$(() => {
  new Vue({
    el: '#app',
    render: h => h(App)
  })
})
```

**Comment by somazx** [comment]
I am wondering if expecting document.body to be present before anything is mounted is a problematic?

What about taking that bit of code:

```
// Refers to https://davidwalsh.name/detect-scrollbar-width
const div = document.createElement('div')

div.style.width = '100px'
div.style.height = '100px'
div.style.overflow = 'scroll'
div.style.position = 'absolute'
div.style.top = '-9999px'

document.body.appendChild(div) /* <---- ERROR IS THIS LINE */

const SCROLLBAR_WIDTH = div.offsetWidth - div.clientWidth
```

And make it a function that is only called when component is mounted?

**Comment by kenberkeley** [comment]
Sounds like a good idea

**Comment by kenberkeley** [comment]
npm i -S vue2-datatable-component@2.1.20

**Comment by kenberkeley** [comment]
Thanks for your feedback! Cheers!

**Comment by somazx** [comment]
Fixed! Thanks for your quick response.
