### ISSUE TITLE
Error in mounted hook: "ReferenceError: $ is not defined"

### ISSUE THREAD

**Issue by greenpdx** [OneWayTech/vue2-datatable#44]
I first ran into issue #30 and fixed it now I am have this error.
Error in mounted hook: "ReferenceError: $ is not defined"

My html look like 
```
    <div v-if="showTable">
      <code>query: {{ dataTable.query }}</code>
      <datatable
        v-bind="dataTable"/>
    </div>
```
my data is
```
      dataTable: {
        data: [],
        query: {},
        total: 10,
        columns: [
          { title: 'Name', field: 'name', sortable: true },
          { title: 'Length', field: 'len', sortable: true },
          { title: 'Access', field: 'access', sortable: true },
          { title: 'Bit Rate', field: 'bit_rate', sortable: true },
          { title: 'Duration', field: 'duration', sortable: true },
          { title: 'Size', field: 'width' }
        ]
      }
```
I send a RPC request for data and display the result
```
    clk_b (evt) {
      this.sendRpc('say_bye', [42, 23], (full) => {
        let data = JSON.parse(full.result)
        console.log('Bye', data)
        this.showTable = true
        this.dataTable.data = data
      })
    },
```
the picture is
![vue-datatable-bad](https://user-images.githubusercontent.com/4604678/33303014-16c221a2-d3b5-11e7-9289-213a88045975.png)

found in

---> <HeaderSettings> at node_modules/vue2-datatable-component/src/HeaderSettings/index.vue
       <Datatable> at node_modules/vue2-datatable-component/src/index.vue
         <HelloWorld> at src/components/HelloWorld.vue
           <App> at src/App.vue
             <Root>

**Comment by kenberkeley** [comment]
Is jQuery + BootStrap available globally?

**Comment by greenpdx** [comment]
That makes sense.  I do not want to use a component that uses jQuery, Thanks anyway

**Comment by disarticulate** [comment]
probably update your docs to indicate a dependency on jquery. 

People are using vuejs as a way to avoid large scale dependencies like jquery.

**Comment by kenberkeley** [comment]
@disarticulate 

![image](https://user-images.githubusercontent.com/13287948/35190371-a06a3de4-fe9a-11e7-9450-f695d4d76148.png)

**Comment by giannisdag** [comment]
So, this component depends on jquery or just bootstrap.css?

**Comment by kenberkeley** [comment]
@giannisdag https://github.com/OneWayTech/vue2-datatable/blob/master/examples/src/index.html

**Comment by giannisdag** [comment]
ok, thank you

**Comment by ncjones** [comment]
@disarticulate did you find a Vue data table component which doesn't depend on jquery?

**Comment by greenpdx** [comment]
I wrote my own because I am using active data.  When I change one value the other values change
https://taxnvote.org

**Comment by disarticulate** [comment]
@ncjones I went with barebones:
https://github.com/richardtallent/vue-scrolling-table-sample

**Comment by ncjones** [comment]
I'm now looking at https://github.com/spatie/vue-table-component.

**Comment by kenberkeley** [comment]
Hereon, I apologize for my poor project, which can not meet all the requirements for everyone...

**Comment by greenpdx** [comment]
I like tables that I can create a component for the row

**Comment by greenpdx** [comment]
@kenberkely, You are doing great, thanks for the effort

**Comment by kenberkeley** [comment]
Well, but I have to say, with the power of jQuery, you are able to implement some tricky features

e.g. https://github.com/OneWayTech/vue2-datatable/blob/master/plugins/HeaderSettingsDnD.js

**Comment by ebgreen** [comment]
Most of the jQuery in this project seems replaced easily enough

Except for the DnD.

**Comment by disarticulate** [comment]
i think the readme should show the dependencies, which is where I lazily started.
