### ISSUE TITLE
Is there a way to let the user resize column width?

### ISSUE THREAD

**Issue by ralphamale** [OneWayTech/vue2-datatable#46]
Thanks!

**Comment by kenberkeley** [comment]
you might have to customize this feature yourself
https://onewaytech.github.io/vue2-datatable/doc/#/en/DIY

**Comment by kenberkeley** [comment]
http://www.bacubacu.com/colresizable/#samples

**Comment by kenberkeley** [comment]
![image](https://user-images.githubusercontent.com/13287948/33354547-5b969530-d4ee-11e7-91f9-863c91b70659.png)

**Comment by kenberkeley** [comment]
I think this plugin should work, but you have to adjust the style to make it look normal
