### ISSUE TITLE
Documentation and Examples not working

### ISSUE THREAD

**Issue by pkerspe** [OneWayTech/vue2-datatable#47]
neither the documentation nor the examples are working. Where to find a basic documentation on the usage of vue2-datatable?

**Comment by kenberkeley** [comment]
Use Chrome to visit:
* https://onewaytech.github.io/vue2-datatable/doc
* https://onewaytech.github.io/vue2-datatable/examples/dist

**Comment by pkerspe** [comment]
Using Chrome Version 62.0.3202.89 (64-Bit), none of the links seems to work :-(

**Comment by kenberkeley** [comment]
https://onewaytech.github.io/vue2-datatable/examples/dist/index.html

**Comment by kenberkeley** [comment]
https://onewaytech.github.io/vue2-datatable/doc/#/

**Comment by pkerspe** [comment]
oh, I am so sorry, all my fault. I had an Ad Blocker active, that killed it.
Closing this issue. Sorry again!

**Comment by kenberkeley** [comment]
I also use ABP but I don't have this problem
