### ISSUE TITLE
Unexpected token: name (scrollWidth)

### ISSUE THREAD

**Issue by reposys** [OneWayTech/vue2-datatable#48]
I'm having an error when building nuxtjs applications 
`npm run build`

Output:
_ERROR in common.a99f74b351f8a391ae27.js from UglifyJs_
Unexpected token: name (scrollWidth) [./node_modules/vue2-datatable-component/src/_utils/getScrollWidth.js:2,0][common.a99f74b351f8a391ae27.js:10963,4]_

If you do not use UglifyJs, then everything is successful.

How can this problem be solved?

**Comment by kenberkeley** [comment]
According to https://onewaytech.github.io/vue2-datatable/doc/#/en/getting-started

```js
// Webpack configuration
module: {
  rules: [
    {
      test: /\.js$/,
      loader: 'babel-loader?cacheDirectory',
      include: [
        <path to source directory>,
        /vue2-datatable-component/ // <-- add this!
      ]
    }
  ]
}
```

**Comment by reposys** [comment]
Yes, that's exactly what I do.

**nuxt.config.js**

const webpack = require('webpack')

module.exports = {
  /*
  ** Headers of the page
  */
  head: {
    title: 'ProjectName',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: 'ProjectName' }
    ],
    link: [
        { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' },
        { rel: 'stylesheet', href: 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css', integrity: 'sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u', crossorigin: 'anonymous' }
    ],
    script: [
        { src: 'https://code.jquery.com/jquery-3.2.1.slim.min.js', type: 'text/javascript', integrity: 'sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN', crossorigin: 'anonymous' },
        { src: 'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js', type: 'text/javascript', integrity: 'sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4', crossorigin: 'anonymous' },
        { src: 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js', type: 'text/javascript', integrity: 'sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa', crossorigin: 'anonymous' }
    ]
  },
  /*
  ** Customize the progress bar color
  */
  loading: false,
  //loading: { color: '#3B8070' },

  css: ['~assets/css/dashboard.css', '~assets/css/main.css'],

  mode: 'spa',

  plugins: [{src: '~/plugins/vue-datatable', ssr: false}, {src: '~/plugins/vue-notification', ssr: false}],

  /*
  ** Build configuration
  */
  build: {
    vendor: ['axios', 'vue2-datatable-component', 'vue-notification'],

    extend (config, ctx) {
      config.module.rules.push({
        test: /\.js$/,
        loader: 'babel-loader?cacheDirectory',
        include: [
          /vue2-datatable-component/
        ]
      })
    }
  }
}

**Comment by kenberkeley** [comment]
I've never used Nuxt.js, so I might not be able to help...
Take a look at the build version: https://github.com/OneWayTech/vue2-datatable/tree/master/dist
