### ISSUE TITLE
Tried using fix headers and columns

### ISSUE THREAD

**Issue by dummyjaysel** [OneWayTech/vue2-datatable#49]
Hi! Just tried the fix column to display fix column and some dynamic scrollable columns next to it and so I set the columns that are fixed to 'fixed: true'. The column duplicates when i set it to fixed.
![image](https://user-images.githubusercontent.com/22280794/33701336-50adff7a-db59-11e7-8113-ca89545d4df1.png)

Here is my code on my table:

      fixHeaderAndSetBodyMaxHeight: 200,
      tblStyle: 'table-layout: fixed',
      tblClass: 'table-bordered',
      columns: [
        {
          title: 'Item Code',
          field: 'itemCode',
          thComp: 'FilterTh',
          sort: true,
          fixed: true
        },
        {
          title: 'Item Name',
          field: 'itemName',
          sort: true,
          fixed: true
        },
        {
          title: 'UOM',
          field: 'uom',
          sort: true,
          fixed: true
        }
      ],
      data: [],
      total: 0,
      selection: [],
      query: {},
      fieldCols: ['itemCode', 'itemName', 'uom']

Thank you so much. Hope you can help me with this :)

**Comment by kenberkeley** [comment]
Accoring to the example: https://github.com/OneWayTech/vue2-datatable/blob/master/examples/src/Fixed/index.vue#L21

you have to set the width of the columns yourself.

**Comment by dummyjaysel** [comment]
Adding the setting of width code displays an error.
![image](https://user-images.githubusercontent.com/22280794/33703256-53e7831a-db62-11e7-8762-a9ce296b7571.png)

**Comment by kenberkeley** [comment]
These are ESLint problems, you should know how to fix them

**Comment by dummyjaysel** [comment]
Uhhh. Okay thanks! 👍
