### ISSUE TITLE
[Vue warn]: Do not use built-in or reserved HTML elements as component id: Table

### ISSUE THREAD

**Issue by vaniawahyu** [OneWayTech/vue2-datatable#51]
I followed the guide and success, but my console have this warning.

**Comment by kenberkeley** [comment]
May I ask your Vue.js version?

**Comment by vaniawahyu** [comment]
2.5.10

**Comment by kenberkeley** [comment]
ok, i will fix it in the next minor version

**Comment by kenberkeley** [comment]
`npm i -S vue2-datatable-component@2.1.21`
