### ISSUE TITLE
Deleting a record (the recommended method)

### ISSUE THREAD

**Issue by shaunie2fly** [OneWayTech/vue2-datatable#52]
Hi
Thank you for a great control.  :)  Super flexible and easy to use even as a vue.js beginner.

![image](https://user-images.githubusercontent.com/18495824/34068866-51f5037a-e24c-11e7-9074-09afdb1730a3.png)

There is one thing I'm trying to wrap my head around. What is the best way to delete a row from the table.  

So, I reference the row delete button from the main grid column tdComp.  ie
`{ title: " ", tdComp: "DeleteRowButton", visible: "true" } `
then i would use the `row.id` as the reference in a function from the tdComp template to call an API to delete the record.  But what should i do from there ?  
Should I just filter.array  that entry I deleted from the DB so the datatable updates or should I request an updated dataset from the database to repopulate the datatable data?

Also how to I reference the query and data from the tdComp template ?  I know that's probably a vue.js101 question but i am 101 ;)

Thanks :)

**Comment by kenberkeley** [comment]
`Should I just filter.array that entry I deleted from the DB so the datatable updates or should I request an updated dataset from the database to repopulate the datatable data?`

You should request the API to refresh the list after the row deleted successfully

***

`Also how to I reference the query and data from the tdComp template ?`

According to the [doc](https://onewaytech.github.io/vue2-datatable/doc/#/en/details/dynamic-comps?id=%e2%8a%99-tdcomp), you can access all the props from Datatable

**Comment by kenberkeley** [comment]
If there are no more questions, you may need to close the issue yourself.

**Comment by shaunie2fly** [comment]
Thanks ken :)

**Comment by kenberkeley** [comment]
Do you know why I ask you to refresh the list instead of local filter?

e.g.

```js
this.data = this.data.filter(row => row.id !== deletedRow.id)
```

**Comment by kenberkeley** [comment]
That's because, if `query` is `{ limit: 10, offset: 0, sort: '', order: '' }`

If you remove a row from `this.data`, then only 9 rows remaining, which contradicts `query.limit`

**Comment by shaunie2fly** [comment]
Hi Ken :)

Yes, that did cross my mind.  I was thinking about manually adjusting the
limit when removing the row, but I did start to wonder whether I was
digging myself into a corner :)
