### ISSUE TITLE
it show  Error in mounted hook: "ReferenceError: $ is not defined" aways in the console

### ISSUE THREAD

**Issue by yujunjie0603** [OneWayTech/vue2-datatable#53]
你好

在console里一直显示
[Vue warn]: Error in mounted hook: "ReferenceError: $ is not defined"

found in

---> <HeaderSettings> at node_modules/vue2-datatable-component/src/HeaderSettings/index.vue
       <Datatable> at node_modules/vue2-datatable-component/src/index.vue
         <ListeItem> at src/components/ListeItem.vue
           <Service> at src/components/Service.vue
             <App> at src/App.vue
               <Root>

请问这个是神码问题，谢谢

**Comment by kenberkeley** [comment]
https://github.com/OneWayTech/vue2-datatable/issues/44
