### ISSUE TITLE
Feature Request: Retrieve entire filtered data set. 

### ISSUE THREAD

**Issue by shightower** [OneWayTech/vue2-datatable#54]
Currently you can only retrieve a page at a time, I'd like to be able to apply filtering and retrieve the entire collection.

**Comment by kenberkeley** [comment]
`this.data = allRows.slice(query.offset, query.offset + query.limit)`

**Comment by shightower** [comment]
@kenberkeley I'm not following. Where is allRows coming from? datatable.data contains only the current rows for the page, is there another attribute that holds all the rows with the filter applied?

**Comment by kenberkeley** [comment]
`allRows` is just a cache variable for 500 rows

**Comment by kenberkeley** [comment]
There is no difficulty to implement your scenario

**Comment by kenberkeley** [comment]
```html
<template>
  <datatable v-if="allRows.length" v-bind="$data" :total="allRows.length" />
</template>
<script>
export default {
  data: () => ({
    columns: [
      // ...
    ],
    data: [],
    allRows: [],
    query: {}
  }),
  created () {
    yourApi().then(allRows => {
      this.allRows = allRows
    })
  },
  watch: {
    query: {
      handler (query) {
        this.data = allRows.slice(query.offset, query.offset + query.limit)
      },
      deep: true
    }
  }
}
</script>
```

**Comment by kenberkeley** [comment]
If there are no more question, you might have to close this issue

**Comment by shightower** [comment]
@kenberkeley Thanks for the input but I still don't think the answers the question I had. vue2-datatable seems to take the given original data set, apply  the filter, and then only retain the records needed for the current page. Your suggestion of doing a slice only gets you a sequential set of what was in the original collection, but when applying a filter, there is no guarantee the results will line up like that. 

I'm not sure if I'm not explaining this correctly, but I can't think of another way to describe the scenario than what I did before. If I filter a data set, I'd like to be able to retrieve the new filtered collection without having to iterate through pages. If this still doesn't make sense or you don't think it's a reasonable/feasible ticket I'll just close it. I'm happy to set something up in codesandbox as an example.

**Comment by kenberkeley** [comment]
It's late in China, I got to sleep. Will give u a satisfying reply tomorrow.

**Comment by shightower** [comment]
Closing the ticket. I figured out the solution.
