### ISSUE TITLE
Add type="button" to <button/>

### ISSUE THREAD

**Issue by huqiang** [OneWayTech/vue2-datatable#55]
It is noticed in `HeaderSettings/index.vue`, the `<button/>` tags do not have `type` set, thus the default type `submit` is applied, (https://www.w3.org/TR/html401/interact/forms.html#h-17.5). 

When `vue2-datatable` is used in a page with `form`, the `<button/>` `click` action will trigger a form submit, as well as page refresh.

**Comment by kenberkeley** [comment]
Hmmm... I had never thought of this scenario...

**Comment by kenberkeley** [comment]
`npm i -S vue2-datatable-component@2.1.24`
