### ISSUE TITLE
Fixed column issue: empty / repeat

### ISSUE THREAD

**Issue by shuyan-li** [OneWayTech/vue2-datatable#56]
In [Fixed (headers and columns)](https://onewaytech.github.io/vue2-datatable/examples/dist/#fixed) example, when only selecting the 2 fixed columns, i.e. userID and Country, the display appears as 4 columns, even though Inspect only show 2 columns: 
- an empty column is added after userID.  
- Country column is repeated:  
![image](https://user-images.githubusercontent.com/34930217/34428925-a2a1a22a-ec8c-11e7-800f-110226788652.png)

**Inspect:** 
![image](https://user-images.githubusercontent.com/34930217/34429071-17f2dea8-ec8e-11e7-9346-47e674b2feee.png)

**Comment by kenberkeley** [comment]
If there are just a few columns, why should you use fixed columns?

**Comment by kenberkeley** [comment]
`Fixed column` is a trial feature
