### ISSUE TITLE
Eslint raises syntax error

### ISSUE THREAD

**Issue by m-bryo** [OneWayTech/vue2-datatable#57]
After installing via npm, I get the following issue

ERROR in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vue2-datatable-component/src/index.vue
Module build failed: SyntaxError: Unexpected token (38:59)

  36 |   created () {
  37 |     // init query (make all the properties observable by using `$set`)
> 38 |     const q = { limit: 10, offset: 0, sort: '', order: '', ...this.query }
     |                                                            ^
  39 |     Object.keys(q).forEach(key => { this.$set(this.query, key, q[key]) })
  40 |   },
  41 |   watch: {

 @ ./~/vue2-datatable-component/src/index.vue 7:2-89
 @ ./~/vue2-datatable-component/src/main.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

**Comment by kenberkeley** [comment]
https://github.com/OneWayTech/vue2-datatable/issues/45
