### ISSUE TITLE
HeaderSetting needs Jquery?

### ISSUE THREAD

**Issue by fatb0000** [OneWayTech/vue2-datatable#6]
Hi , I tried the basic example but  "Setting" button in top right corner is not working fine. I checked the source, it seems using jquery. I didn't try to import jquery in my project so I am not sure if it is jquery required. 
e.g. line 90 : https://github.com/OneWayTech/vue2-datatable/blob/master/lib/HeaderSettings/index.vue

**Comment by kenberkeley** [comment]
BootStrap needs jQuery, more details in:
https://onewaytech.github.io/vue2-datatable/docs/_book/en/preface.html
