### ISSUE TITLE
Add custom attribute to table row

### ISSUE THREAD

**Issue by zontarian** [OneWayTech/vue2-datatable#60]
Hi,
I'd like to make a row clickable. I can do it with Boostrap, but now the problem is, I'd like to retrieve the link of the page I'd like to open when the user clicks on a row. Just now I can intercept the click with two lines of JQuery, but I'm unable to retrieve the link t the detail oage,

Ideally I'd add a `data-href="...myapi/resource/{{row.id}}` to the `TR`, as I've done in a static example. 

Is there a way to add custom data to a row TR definition? It would be sufficient to add an attribute with a given value.

Any idea? Thanks
W

**Comment by kenberkeley** [comment]
Why don't you do this in a `tdComp`:

```html
<template>
  <!-- whatever -->
</template>
<script>
export default {
  props: ['row'],
  mounted () {
    $(this.$el).closest('tr').on('click', () => {
      window.open(`...myapi/resource/${this.row.id}`)
    })
  }
}
</script>
```

**Comment by zontarian** [comment]
Hei thanks!
Right now i am not at the pc so i cannot test but are you telling me that thr “this” holds the whole recordset for a row of data?
As retunrd from the APIs?

Thanks!

Walter Gamba
walter@iakta.it
+39 348 5610576
Iakta srl
Via A. Da Montefeltro 2
10134 Torino - Italy

**Comment by kenberkeley** [comment]
Of course dude.
Have you read the doc?

**Comment by zontarian** [comment]
I must confess it’s a bit hard to read at times. I’ll read more thoroughly. 
All in all it’s nice!
Thanks

Walter Gamba
walter@iakta.it
+39 348 5610576
Iakta srl
Via A. Da Montefeltro 2
10134 Torino - Italy

**Comment by kenberkeley** [comment]
Pardon for my Chinenglish

**Comment by zontarian** [comment]
No problem at all. Moreover i still struggle eith Es6 and I’s just afew dsys since i started using Vue..

Thanks for the good work and help!

Walter Gamba
walter@iakta.it
+39 348 5610576
Iakta srl
Via A. Da Montefeltro 2
10134 Torino - Italy

**Comment by kenberkeley** [comment]
Enjoy your frontend voyage!
