### ISSUE TITLE
Advanced List (with Checkboxes) forgets which Rows where selected when paginating

### ISSUE THREAD

**Issue by sscholle** [OneWayTech/vue2-datatable#63]
It can be useful, if not preferable, that the rows which are selected, remain in a selected state when paginating away and returning to that page.

Its non-sensible to select items, then paginate, and loose selection.

**Comment by kenberkeley** [comment]
It's intentional
https://github.com/OneWayTech/vue2-datatable/blob/6965fc442e67c4511cd2fd3439b58110ede003cf/src/Table/MultiSelect.vue#L41
