### ISSUE TITLE
HTML rending in the table

### ISSUE THREAD

**Issue by pkimtani** [OneWayTech/vue2-datatable#66]
Thanks for a great plugin! Cheers to that.

I am trying to insert an Image as td but it displays the url/html syntax instead of rendering it. How do I go ahead with that? I couldn't find anything in the doc or properties mentioning the case.
Also, how do we achieve ajax based data loading and handling (searching)?

**Comment by kenberkeley** [comment]
Did you really read the doc?

**Comment by kenberkeley** [comment]
Any question now?

**Comment by pkimtani** [comment]
Hi, I did go through the doc but couldn't really find what can solve my problem. There's something called tdComp in which I can provide my components, but how do I pass my component properties to the same? For ex: I have an ImageModal component which accepts two props- 1) img src & 2) allowDelete, so how do I pass these two properties for each row and at a column level respectively.

May be I missed out something in the doc, so if you could please help me in locating the place where the same is mentioned.

**Comment by kenberkeley** [comment]
https://onewaytech.github.io/vue2-datatable/doc/#/en/details/dynamic-comps?id=%e2%8a%99-thcomp

**Comment by kenberkeley** [comment]
```html
<template>
  <img :src="row.src">
</template>
<script>
export default {
  props: ['row', 'columns'],
  created () {
    console.log(this.columns)
  }
}
</script>
```

**Comment by pkimtani** [comment]
I will give it shot. Thanks a lot for the help :smiley:

**Comment by kenberkeley** [comment]
Live Examples:
https://github.com/OneWayTech/vue2-datatable/tree/master/examples/src/Advanced/comps
