### ISSUE TITLE
Export feature

### ISSUE THREAD

**Issue by swamy526** [OneWayTech/vue2-datatable#67]
Exporting table data as a file of different formats like pdf, json, csv, tsv..etc
Like https://editor.datatables.net/examples/extensions/exportButtons

**Comment by kenberkeley** [comment]
it would be much better to implement it by the backend

**Comment by Pulstarter** [comment]
Hi!

Although I am agree with kenberkely, I have written a simple component which uses a JQuery plugin to export JSON data:

[excelexportjs plugin repo](https://github.com/tarunbatta/excelexportjs)

Component:


    <template>

        <div>
            <div class="btn-group" role="group" aria-label="Export formats">
                <button type="button" class="btn btn-secondary" @click="exportDataFormat('xls')">XLS</button>
                <button type="button" class="btn btn-secondary" @click="exportDataFormat('json')">JSON</button>
            </div>

            <div id="data-container"></div>
        </div>

    </template>

    <script>
        export default {
            props: ['dataset'],

            methods: {

                getColumns(paramData) {
                    var header = [];
                    $.each(paramData[0], function (key, value) {
                        var obj = {}
                        obj["headertext"] = key;
                        obj["datatype"] = "string";
                        obj["datafield"] = key;
                        header.push(obj);
                    });
                    return header;
                },

                exportDataFormat: function (format) {

                    var self = this;

                    switch (format) {

                        case 'xls':
                            $("#data-container").excelexportjs({
                                containerid: 'data-container',
                                datatype: 'json',
                                dataset: self.dataset,
                                columns: self.getColumns(self.dataset)
                            });
                            break;

                        case 'json':
                            console.log(self.dataset);
                            break;

                    }
                }

            }
        }
    </script>

Then import it and pass your dataset to it. I only made XLS implementations, so feel free to do as many as you need.

Regards

PD: @kenberkely I am in love with this plugin. Thank you very much for it.
