### ISSUE TITLE
Support Shift + Click To Select Multiple Checkbox

### ISSUE THREAD

**Issue by a0902m51** [OneWayTech/vue2-datatable#69]
Sorry my english !
pls, let them same as gmail checkbox.
I can make them same as gmail checkbox but selection function can't detect them all.

Thanks for help !

**Comment by kenberkeley** [comment]
sorry... i dont really understand the scenario

**Comment by kenberkeley** [comment]
you can control the selection by manipulate `selection`

**Comment by a0902m51** [comment]
sorry my english ! Current i am used `selection`.  And I want to increase the user experience.
I use my javascript code for multiple select checkbox with shift + click. When user shift + click first checkbox and last checkbox. it will check all checkbox between them.
 But `selection` detect only first checkbox and last checkbox (realy click).

Can use support it ?
So sorry my english. Just translate.

**Comment by kenberkeley** [comment]
you might have to DIY
