### ISSUE TITLE
not really an issue 

### ISSUE THREAD

**Issue by ebgreen** [OneWayTech/vue2-datatable#71]
I haven't even looked at the code but I would assume saving the filter view to session that exists be easily modified to save to multiple views in the database.

Does that make sense?

Simple answer or quick recommendation to save me time is enough so I can roll my own solution for this. I can imagine it may be as simple as saving some json to the db with a named identifier and then pulling the json back out and applying.

**Comment by kenberkeley** [comment]
you can even pull all the data to the frontend

**Comment by kenberkeley** [comment]
if you have read the code in `examples/src` before, you may realize that cache all the data in the frontend and render them with some conditions is ok

**Comment by kenberkeley** [comment]
but you might be aware of that, the data ain't static as the database keeps CURD all the time

**Comment by kenberkeley** [comment]
close the issue if you have no more questions.

**Comment by ebgreen** [comment]
I just want to save the filter options. I assumed that's what your save did
but it sounds like it saves the data too.

Thanks,


Eric Green

Pitbull Audio/CTO

Cell: (619) 985 - 1270

Email: <admin@pitbullaudio.com>admin@pitbullaudio.com
<eric@expresslyweb.com>

**Comment by kenberkeley** [comment]
```js
locolStorage.setItem('cond1', this.query)
```

**Comment by ebgreen** [comment]
Should be too hard I hope I've already been tweaking it to remove most of
the jquery stuff that can be done in vue easily and to accommodate for b4.


Thanks,


Eric Green

Pitbull Audio/CTO

Cell: (619) 985 - 1270

Email: <admin@pitbullaudio.com>admin@pitbullaudio.com
<eric@expresslyweb.com>

**Comment by ebgreen** [comment]
so that is the query only or both the query and the results of the query.
if it's just the query before the submitting to the backend it shouldn't be
to hard to save that to the database to be used as a preset view.

Thanks,


Eric Green

Pitbull Audio/CTO

Cell: (619) 985 - 1270

Email: <admin@pitbullaudio.com>admin@pitbullaudio.com
<eric@expresslyweb.com>
