### ISSUE TITLE
Is babel required?

### ISSUE THREAD

**Issue by BlaqCox** [OneWayTech/vue2-datatable#72]
I'm fairly new to Vue and webpack so I apologize if the answer to this is obvious to most, but is babel-loader a separate prerequisite to this package? If so, shouldn't it be listed with lodash and bootstrap/fontawesome?

Is vue-loader an alternative that can be used? I'm trying to incorporate this into the ASP.NET Core VueJS SPA template and I'm not having much luck with the setup instructions here: https://onewaytech.github.io/vue2-datatable/doc/#/en/getting-started

Getting this error without the webpack config changes added:
`Module parse failed: D:\Dev\ProtoPortal\node_modules\vue2-datatable-component\src\index.vue Unexpected token (1:0)
You may need an appropriate loader to handle this file type.`

and with:
`Module not found: Error: Can't resolve 'babel-loader' in 'D:\Dev\ProtoPortal'`

[package.json.txt](https://github.com/OneWayTech/vue2-datatable/files/1745804/package.json.txt)
[webpack.config.js.txt](https://github.com/OneWayTech/vue2-datatable/files/1745805/webpack.config.js.txt)

**Comment by kenberkeley** [comment]
dependencies are different from devDependencies
