### ISSUE TITLE
Is there any way to render html inside rows

### ISSUE THREAD

**Issue by ErBahuguna** [OneWayTech/vue2-datatable#75]
I need to display raw HTML content inside rows.
Is there any way to achieve this?

**Comment by kenberkeley** [comment]
Are you talking about *nested component*?

**Comment by ErBahuguna** [comment]
Not nested actually i need to use something like
<a href="http://www.abc.com">Click me</a> in one column

**Comment by kenberkeley** [comment]
Oh I got you: `tdComp` is what you looking for

**Comment by ErBahuguna** [comment]
Can i have example on this. How can i use this ?

**Comment by kenberkeley** [comment]
take a look at the online examples on README

**Comment by kenberkeley** [comment]
good night i got to sleep

**Comment by ErBahuguna** [comment]
Thanks for the support.
