### ISSUE TITLE
nothing search

### ISSUE THREAD

**Issue by rofiuddin15** [OneWayTech/vue2-datatable#8]
I can't add search componencts, not in documentation. please give me how to do it.

**Comment by kenberkeley** [comment]
Refer to https://github.com/OneWayTech/vue2-datatable/blob/master/examples/src/Advanced/comps/th-Filter.vue

**Comment by kenberkeley** [comment]
They are just [dynamic components](https://vuejs.org/v2/guide/components.html#Dynamic-Components), no magic.

**Comment by kenberkeley** [comment]
For more details, take a look at the [source](https://github.com/OneWayTech/vue2-datatable/blob/master/lib/index.vue#L22-L24)

**Comment by rofiuddin15** [comment]
Ok thanks for the solution, i will try it
