### ISSUE TITLE
LTS timeline and milestones. 

### ISSUE THREAD

**Issue by ashbeats** [OneWayTech/vue2-datatable#80]
I like this project. Personally, the comp is quite simple to implement and extend once you get past the documentation and actually step through the source code. 

Code is on point.

... but as a dependecy for production, it requires a little more firm direction. 

I suggest adding a timeline for targeting a LTS roadmap and a contributing rules to the wiki.

If you're not planning to have an l.t.s release, do let us know as well.

Thanks.

**Comment by kenberkeley** [comment]
Marked

**Comment by kenberkeley** [comment]
2.2.x is a LTS

**Comment by kenberkeley** [comment]
Wiki is not necessary
Any PR is welcome and could be casual 'cause I will optimize it finally
I will keep the [releases](https://github.com/OneWayTech/vue2-datatable/releases) active from now on
