### ISSUE TITLE
Nested Components After Pagination

### ISSUE THREAD

**Issue by sam-araiza** [OneWayTech/vue2-datatable#83]
Hey, I was wondering if you could give me a hand.

I'm binding the data (or rows) to a computed function because the data that populates the table can be changed on state. This is no problem for the initial render, but after I go on to the second page, I lose my observers, and my triggers to expand the nested rows don't function. nested.$toggle(comp, true) doesn't work as expected. 

Do you have any advice on how to best go about adding observers after the second page? Data is being applied via AJAX.

**Comment by kenberkeley** [comment]
computed data is not supported... using `watch` instead

**Comment by kenberkeley** [comment]
https://github.com/OneWayTech/vue2-datatable/blob/master/src/index.vue#L41-L100

**Comment by sam-araiza** [comment]
Thanks, I'll check it out!

**Comment by sam-araiza** [comment]
In case anybody runs into this issues, I resolved by the following:
1. leaving data: [] in the component's data() store
2. watching my computed array and looping through the array for each paginated result and running
`this.$set(this.data, rowIndex, rowObj)`

That tells Vue to reset observers on technically the same array with new data.
