### ISSUE TITLE
Cannot create Custom buttons on Actions

### ISSUE THREAD

**Issue by gwiwoloku** [OneWayTech/vue2-datatable#84]
Hi,

I have been trying to add custom buttons on the appropriate field, tried using the components but it seems not to be rendering and to be honest couldn't understand much from the documentation .

When I insert tdcomp : Opt where is that referencing to?  any help?

**Comment by gwiwoloku** [comment]
and also is there a better way to call a nested object in the column as mapping the data into a new row in the array doesn't seem the best way? Thanks

**Comment by kenberkeley** [comment]
did u check out the examples?

**Comment by gwiwoloku** [comment]
Yeah, checked the examples but its not rendering the components, it seems just like is skipping them.

I have called it and its showing as a component but its not rendering anything on the table

**Comment by kenberkeley** [comment]
did you register the component?

**Comment by gwiwoloku** [comment]
![vdata01](https://user-images.githubusercontent.com/13569703/37036259-019a2ed4-2147-11e8-9e70-c65a3e394373.png)
Yes

**Comment by gwiwoloku** [comment]
the operations td comes back as empty! Don't really know why, it has been registered , I am not passing no data there but still it should render

**Comment by kenberkeley** [comment]
you really should follow the examples

**Comment by kenberkeley** [comment]
or... register globally

**Comment by kenberkeley** [comment]
register the components as I do, OK?

**Comment by kenberkeley** [comment]
Obviously, you did not register the components as I do
