### ISSUE TITLE
Inline cell editing

### ISSUE THREAD

**Issue by laurentlemaire** [OneWayTech/vue2-datatable#85]
Would you have an example of how to enable inline cell editing (if possible) with this component?
I've seen that there is a dynamic component support but not sure on how it would work.

Thanks

**Comment by laurentlemaire** [comment]
Thanks for you reply, but I dont see any reference to this in the documentation.

"isEditing: true" on the datatable compoment?
And where would I use the v-if?

The way I use this component is that I pass a data array + column definition array and it generates the table for me. On what could I apply any v-if there?
Maybe there is a way to update cell content to use a specific component instead of displaying text, but is this done trough some parameters or do I need to fork and update templates?

Thanks,

**Comment by kenberkeley** [comment]
```html
<template>
  <div v-if="isEditing">
    <input ref="input" type="text" :value="value" />
    <button @click="save">OK</button>
    <button @click="isEditing = false">Cancel</button>
  </div>
  <div v-else>
    {{ value }}
    <button @click="isEditing = true">Edit</button>
  </div>
</template>
<script>
export default {
  props: ['row', 'value'],
  data: () => ({
    isEditing: false
  }),
  methods: {
    save () {
      const { value } = this.$refs.input
      xxxApi({ value }).then(() => {
        this.row.xxx = value // sync with props.row
      })
    }
  }
}
</script>
```

**Comment by kenberkeley** [comment]
Anymore questions?
