### ISSUE TITLE
Assign row-field nested object property

### ISSUE THREAD

**Issue by maltere** [OneWayTech/vue2-datatable#86]
Hey there folks,
I am trying to solve an issue, with the field property and some nested object in a row. 
I did not find an answer for this project, but I was trying to use the syntax from datatables.net

I have a row object that looks basically like this: 
`{ name: "Max", user: { email: "testvalue" }}`

I am trying to add a two columns to my datatable:
```
{ title: 'Name', field: 'name', sortable: true },
{ title: 'E-Mail', field: 'user.email' }
```

now my email column does not contain any data.

What would be the recommended solution to this problem?

Thanks!

**Comment by kenberkeley** [comment]
https://github.com/OneWayTech/vue2-datatable/issues/86

**Comment by kenberkeley** [comment]
https://github.com/OneWayTech/vue2-datatable/issues/15
