### ISSUE TITLE
Add tdComp:  blank

### ISSUE THREAD

**Issue by agungid** [OneWayTech/vue2-datatable#9]
Hi. I'm having trouble composing tdComp. The element I created is not showing. Is there something missing?
Code https://pastebin.com/WTu9ege4

**Comment by kenberkeley** [comment]
Pardon me for replying so late.
Have you solved the problem?

**Comment by kenberkeley** [comment]
Line65：`</dvi>`

**Comment by agungid** [comment]
Not yet. I fixed it but still blank.
```
<template>
  <div>
    <button class="btn btn-default" title="Edit">
      <i class="fa fa-pencil"></i>
    </button>
  </div>
</template>
```

**Comment by kenberkeley** [comment]
Any snapshot? Any console error message?

**Comment by agungid** [comment]
In the console there is no error
![duaaa](https://user-images.githubusercontent.com/11351024/29506801-a55a53a2-8677-11e7-94a6-44e02d7c5598.png)
![satu](https://user-images.githubusercontent.com/11351024/29506800-a5485418-8677-11e7-8052-a616b931197e.png)

**Comment by kenberkeley** [comment]
It seems that `Opt` is unavailable.
Try: in Vue devtools, select `Datatable` in the component tree. Then execute `$vm.comp` in the console

**Comment by kenberkeley** [comment]
The console should output `Object { Opt: XXX }` if everything's alright

**Comment by agungid** [comment]
![empat](https://user-images.githubusercontent.com/11351024/29507353-d88f6a3a-8679-11e7-9a23-92ec052281d4.png)
![tiga](https://user-images.githubusercontent.com/11351024/29507352-d87af870-8679-11e7-9b7c-ec348d801319.png)

**Comment by kenberkeley** [comment]
Very strange...

**Comment by kenberkeley** [comment]
It couldn't be possible...

**Comment by agungid** [comment]
@kenberkeley Is there any other solution to this problem?

**Comment by cosmic-fibre** [comment]
@kenberkeley can you elaborate more please?

**Comment by kenberkeley** [comment]
Register `Opt` component globally please

**Comment by kenberkeley** [comment]
Is that OK?

**Comment by agungid** [comment]
Still not able. The code is like this
https://pastebin.com/k08MkyxE

**Comment by kenberkeley** [comment]
You should `Vue.component('Opt', components.Opt)`

**Comment by agungid** [comment]
Yeah this works.
But if the register to global what will not be a problem?

**Comment by kenberkeley** [comment]
Oh I see.
https://pastebin.com/k08MkyxE Line11 and Line47.
`components` conflicts, so the latter one override the former

**Comment by kenberkeley** [comment]
At the beginning, the code in https://pastebin.com/WTu9ege4 did not appear this problem.
That's why I felt so strange.

**Comment by kenberkeley** [comment]
It would be better to present an integrity example next time.

**Comment by agungid** [comment]
I have changed like this. But it did not work
```
import cmp from './cmp/'
export default {
  cmp,
 .......
}
```

**Comment by agungid** [comment]
Successful if registered in global

**Comment by kenberkeley** [comment]
Why not trying:
```js
components: {
  addPartisipant,
  editPartisipant,
  ...cmp
}
```

**Comment by kenberkeley** [comment]
Checkout Vue.js official docs: https://vuejs.org/v2/guide/components.html#Local-Registration

**Comment by agungid** [comment]
Thanks. This works well

**Comment by kenberkeley** [comment]
It is suggested using ESLint to avoid these mistakes.

**Comment by agungid** [comment]
Ok, thank you
