### ISSUE TITLE
Server side processing

### ISSUE THREAD

**Issue by hhsadiq** [OneWayTech/vue2-datatable#91]
Hi guys,
We are planning to use this plugin for our production system. Just want to confirm that this plugin supports server-side processing similar to https://datatables.net/examples/data_sources/server_side.html ?

Thanks

**Comment by kenberkeley** [comment]
Might not...

**Comment by hhsadiq** [comment]
Thanks for quick reply.

So that means if we would like to load records from server, and add server-side pagination and search ability, it is not possible right now?

**Comment by kenberkeley** [comment]
Actually I haven't tried yet
You can have a try

**Comment by kenberkeley** [comment]
I said 'might not' since this plugin relies on jQuery etc

**Comment by hhsadiq** [comment]
Ic, ok.

**Comment by kenberkeley** [comment]
server-side rendering is not necessary for datatable pages, IMHO
