### ISSUE TITLE
syntax error unexpected token, build failed!

### ISSUE THREAD

**Issue by medmans** [OneWayTech/vue2-datatable#93]
Hello,

i installed vue2-datatable in my vuejs application and i imported it as described in the documentation.

but, i had an error localised in the index.vue file

> ERROR in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./node_modules/vue2-datatable-component/src/index.vue
> Module build failed: SyntaxError: Unexpected token (38:59)

> const q = { limit: 10, offset: 0, sort: '', order: '', ...this.query }

 in this index **...this.query**

**Comment by medmans** [comment]
i solved this with adding `stage-3` to presets in .babelrc like this:

```
"presets": [
    ["env", { "modules": false }],
    "stage-3"
 ]
```

**Comment by kenberkeley** [comment]
https://github.com/OneWayTech/vue2-datatable/issues/12
