### ISSUE TITLE
Add Pending feature

### ISSUE THREAD

**Issue by maltere** [OneWayTech/vue2-datatable#95]
Hey there,

for the purpose of asynchronous loading, I want to implement a Spinner at the place where currently the Table is located. I do not want to hide the whole component. 

My Proposal would be wrap the `tbl`-component

`<slot name="table"><tbl v-bind="$props" /></slot>`

in your own code you can then use the v-if statement as followed

```
<datatable v-bind="$data" class="datatable">
        <div>This goes to default slot</div>
        <div slot="table" v-if="pending">This is there instead of the table while pending is true</div>
</datatable>
```

worked for me so far

**Comment by kenberkeley** [comment]
Well... that is why I suggested DIY

**Comment by kenberkeley** [comment]
Use your own forked might be better, since this repo is highly stable and I am no longer work for OneWay...
